Add Digger
PortsMaster/PortMaster-New pull request #1006
Opened 2024-12-04 06:42 UTC by Slayer366

# New Port for Digger

## Game Information
- **Title**: Digger
- **URL**: [sobomax](https://github.com/sobomax/digger)

### CFW Tests
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
- [x] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-12-04 11:27 UTC, kloptops submitted a review, later dismissed

2024-12-04 13:00 UTC, Cebion requested changes

2024-12-04 13:08 UTC, Slayer366 commented on ports/digger/README.md
Would you mind tossing them my way?  According to the Readme and the thread in Discord, you helped EvilLurker to compile it and I think there was something special you did to recompile it for AmberELEC so I'm not sure what I should put for that.

2024-12-04 18:29 UTC, Cebion submitted a review, later dismissed

2024-12-05 03:26 UTC, cdeletre requested changes

2024-12-05 03:59 UTC, Slayer366 commented on ports/digger/port.json
> +    "image": "digger.screenshot.png",
I agree.  I can remove that.  It was in EvilLurker's old port.json like this.  There's actually no real need to leave it here.  I also realized that I renamed the image so this is wrong anyway lol.

2024-12-05 04:03 UTC, Slayer366 commented on ports/digger/port.json
> +    "image": "digger.screenshot.png",
Good catch

2024-12-05 07:44 UTC, Cebion approved these changes

2024-12-06 17:18 UTC, cdeletre approved these changes

2024-12-06 17:22 UTC, merged