Pixel Descent
PortsMaster/PortMaster-New pull request #1008
Opened 2024-12-04 09:22 UTC by tabreturn

# New Port for Pixel Descent

## Game Information
- **Title**: Pixel Descent
- **URL**: https://jc-bailey.itch.io/pixel-descent

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-12-04 09:24 UTC, Cebion approved these changes

2024-12-04 11:15 UTC, kloptops requested changes

2024-12-04 11:15 UTC, kloptops commented on ports/pixeldescent/Pixel Descent.sh
> +pm_platform_helper "gmloadernext.aarch64"
This should be the full path.
```suggestion
pm_platform_helper "$GAMEDIR/gmloadernext.aarch64"
```

2024-12-04 14:06 UTC, cdeletre commented on ports/pixeldescent/Pixel Descent.sh
> +$ESUDO chmod +x -R $GAMEDIR/*
```suggestion
$ESUDO chmod +x $GAMEDIR/gmloadernext.aarch64
$ESUDO chmod +x $GAMEDIR/tools/splash
```

2024-12-04 14:08 UTC, cdeletre commented on ports/pixeldescent/Pixel Descent.sh
> +$ESUDO ./tools/splash "splash.png" 2000
```suggestion
$ESUDO ./tools/splash "splash.png" 2000 &
```

2024-12-04 14:09 UTC, cdeletre commented on ports/pixeldescent/pixeldescent/lib/armeabi-v7a/libc++_shared.so
can be removed

2024-12-04 14:09 UTC, cdeletre commented on ports/pixeldescent/pixeldescent/lib/armeabi-v7a/libcompiler_rt.so
can be removed

2024-12-04 14:10 UTC, cdeletre commented on ports/pixeldescent/pixeldescent/lib/armeabi-v7a/libm.so
can be removed

2024-12-04 14:10 UTC, cdeletre commented on ports/pixeldescent/pixeldescent/gmloadernext.aarch64
Please add [license](https://github.com/PortsMaster/PortMaster-New/blob/bfc4fdd388344efdc65edced36c1002c93a7e334/ports/darkdeity/darkdeity/license/LICENSE.gmloader.md)

2024-12-05 03:21 UTC, cdeletre approved these changes

2024-12-05 07:43 UTC, Cebion approved these changes

2024-12-05 07:43 UTC, merged