New Port: Super Glitter Rush
PortsMaster/PortMaster-New pull request #1022
Opened 2024-12-07 17:56 UTC by Ganimoth

# New Port for Super Glitter Rush

## Game Information
- **Title**: Super Glitter Rush 
- **URL**: https://tinycactus.itch.io/superglitterrush 

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-12-08 03:47 UTC, tabreturn submitted a review, later dismissed

2024-12-08 16:28 UTC, Cebion requested changes

2024-12-08 16:28 UTC, Cebion commented on ports/superglitter/Super Glitter Rush.sh
> +$ESUDO chmod +x -R $GAMEDIR/*
```suggestion
$ESUDO chmod +x $GAMEDIR/gmloadernext.${DEVICE_ARCH}
```

2024-12-08 19:04 UTC, Cebion approved these changes

2024-12-09 21:03 UTC, tabreturn approved these changes

2024-12-09 21:48 UTC, Slayer366 approved these changes

2024-12-09 21:48 UTC, merged