New Port Thy Sword
PortsMaster/PortMaster-New pull request #1045
Opened 2024-12-13 13:09 UTC by Fraxinus88

# New Port for Thy Sword

## Game Information
- **Title**: Thy Sword
- **URL**: https://store.steampowered.com/app/560300/Thy_Sword/ OR https://gamephase.itch.io/thy-sword

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-12-13 13:24 UTC, Cebion requested changes
Please review your old successful PRs for the .sh changes you did previously. If we review for example that echo is replaced by pm_message please don't use older templates without these changes. Else we'll have to request the same changes on every PR.

2024-12-14 04:17 UTC, cdeletre requested changes

2024-12-14 04:17 UTC, cdeletre commented on ports/thysword/Thy Sword.sh
> +export SDL_GAMECONTROLLERCONFIG="`pm_message "$SDL_GAMECONTROLLERCONFIG" | "$GAMEDIR/tools/SDL_swap_gpbuttons.py" -l "$GAMEDIR/SDL_swap_gpbuttons.txt"`"
```suggestion
export SDL_GAMECONTROLLERCONFIG="`echo "$SDL_GAMECONTROLLERCONFIG" | "$GAMEDIR/tools/SDL_swap_gpbuttons.py" -l "$GAMEDIR/SDL_swap_gpbuttons.txt"`"
```

;)

2024-12-14 04:17 UTC, cdeletre commented on ports/thysword/Thy Sword.sh
> +    pm_message "Error: Missing files in gamedata folder or game has been patched."
```suggestion
```

I think we don't want to give an error message on each start once the game has been patched.

2024-12-14 04:17 UTC, cdeletre commented on ports/thysword/Thy Sword.sh
> +  pm_message "This port requires the latest PortMaster to run, please go to https://portmaster.games/ for more info." > /dev/tty0
```suggestion
  pm_message "This port requires the latest PortMaster to run, please go to https://portmaster.games/ for more info."
```

2024-12-14 15:22 UTC, cdeletre approved these changes

2024-12-14 20:15 UTC, Cebion approved these changes

2024-12-14 20:15 UTC, merged