Blood: Correct library path
PortsMaster/PortMaster-New pull request #1099
Opened 2024-12-27 15:30 UTC by ben-willmore

Blood.sh has a hard-coded path in LD_LIBRARY path that doesn't point to the intended folder on all platforms. This should be relative to $GAMEDIR instead.

2024-12-27 16:16 UTC, Cebion requested changes

2024-12-27 16:16 UTC, Cebion commented on ports/blood/Blood.sh
> +export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GAMEDIR/lib:/usr/lib"
```suggestion
export LD_LIBRARY_PATH="$GAMEDIR/lib:/usr/lib:$LD_LIBRARY_PATH"
```

2024-12-28 12:55 UTC, Cebion approved these changes

2024-12-28 14:17 UTC, JeodC approved these changes

2024-12-28 14:18 UTC, merged