fix to_lower_case() to work correctly on vfat partitions
PortsMaster/PortMaster-New pull request #1107
Opened 2024-12-29 01:25 UTC by bmdhacks

This was preventing these three games from running on CrossmixOS, which uses a FAT partition for ports.
Tested Fallout 1 after this and it works.

2024-12-29 21:47 UTC, Cebion commented
Will need to test this later on the other cfws just to be sure =)

2025-01-02 09:01 UTC, Cebion requested changes
Works good so far. Only thing now is we don't use echo anymore. 
We use the function pm_message "message"

For understanding we do inside pm when we load control.txt 

```

pm_message() {
    # Usage: pm_message "Some message here."
    if [[ "$CFW_NAME" == "muOS" ]]; then
        /opt/muos/extra/muxstart "$1"
    else
        echo "$1" > $CUR_TTY
    fi
}```

2025-01-03 15:44 UTC, cdeletre commented
> Works good so far. Only thing now is we don't use echo anymore. We use the function pm_message "message"

I think it's ok here as it will go into the log.txt, I don't think we want a popup on the screen for this kind of information ?

2025-01-03 16:49 UTC, bmdhacks commented
Just to clarify, the usage of echo was already there.  My change only adds a halfway step to not `mv "FOO"  "foo"` on a fat filesystem.

2025-01-04 08:41 UTC, Cebion approved these changes

2025-01-04 08:41 UTC, merged