Port commit: Savant Ascent
PortsMaster/PortMaster-New pull request #141
Opened 2024-03-01 20:33 UTC by JanTrueno

# New Port for { Game Title }

## Game Information
- **Title**: { Savant Ascent }
- **URL**: { https://store.steampowered.com/app/259530/Savant__Ascent/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-03-02 09:24 UTC, kloptops requested changes
Just need to change this bit, otherwise looks good.

2024-03-02 09:24 UTC, kloptops commented on ports/savant/Savant Ascent.sh
> +if [ "$OS_NAME" == "JELOS" ]; then
Change this to use the mod_${CFW_NAME}.

Below source device_info.txt
```bash
source $controlfolder/device_info.txt

[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
```

2024-03-02 09:29 UTC, Cebion requested changes
if [ -f "/etc/os-release" ]; then
  source "/etc/os-release"
fi 

Is not used since that is in device_info already
also Screenshot needs to show gameplay not the title.

2024-03-02 19:15 UTC, JanTrueno commented
- Fixed .sh file
- Different screenshot to show gameplay

Thanks for the feedback guys :)

2024-03-03 12:32 UTC, Cebion requested changes
We don't use 
```
if [ "$OS_NAME" == "JELOS" ]; then
export SPA_PLUGIN_DIR="/usr/lib32/spa-0.2"
export PIPEWIRE_MODULE_DIR="/usr/lib32/pipewire-0.3/"
fi 
```
This is now in the mod_jelos file and is called `[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"`

2024-03-04 13:34 UTC, kloptops approved these changes
👍

2024-03-04 14:37 UTC, merged