New Port: Tricky Keys
PortsMaster/PortMaster-New pull request #200
Opened 2024-03-21 12:30 UTC by mhoogcarspel

# New Port for Tricky Keys

## Game Information
- **Title**: Tricky Keys
- **URL**: https://saturnyoshi.itch.io/tricky-keys

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-03-21 12:34 UTC, Cebion submitted a review, later dismissed

2024-03-22 12:39 UTC, kloptops requested changes
needs a change to the libgl import.

2024-03-22 12:39 UTC, kloptops commented on ports/trickykeys/Tricky Keys.sh
> +if [ -f "${controlfolder}/libgl_${CFWNAME}.txt" ]; then
this needs to be moved after you cd into `$GAMEDIR`. :)

2024-03-23 04:50 UTC, kloptops approved these changes
👍

2024-03-23 04:51 UTC, merged