Added in Balatro card game
PortsMaster/PortMaster-New pull request #219
Opened 2024-03-23 22:41 UTC by nkahoang

# New Port for Balatro card game

## Game Information
- **Title**: Balatro
- **URL**: [{ Link to project page or source control page }](https://github.com/nkahoang/PortMaster-Balatro/blob/main/ports/balatro/README.md)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS
Proof of running: https://www.reddit.com/r/SBCGaming/comments/1bgtqf2/guideshowcase_i_ported_balatro_to_the_rgb30/

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-03-24 18:45 UTC, Cebion commented
Waiting for Testing in https://discord.com/channels/1122861252088172575/1221238851259994213
Looks promising.

2024-04-01 11:31 UTC, mhoogcarspel commented
I would include a copy of the OFL license for the Nunito font used:
https://github.com/googlefonts/nunito/blob/main/OFL.txt

as we're distributing it as a font file, not embedded:
https://openfontlicense.org/how-to-use-ofl-fonts/

> The only situation in which an OFL font can be distributed without the text of the OFL (either in a separate file or in font metadata), is when a font is embedded in a document or bundled within a program.

2024-04-01 12:30 UTC, kloptops requested changes
Just needs arch change otherwise looks good.

2024-04-01 12:40 UTC, nkahoang commented on ports/balatro/port.json
> +        "reqs": []
Fixed

2024-04-01 12:40 UTC, JeodC approved these changes
Looks good post-changes

2024-04-01 21:15 UTC, JeodC approved these changes

2024-04-01 21:18 UTC, Cebion approved these changes

2024-04-01 21:21 UTC, merged

2024-06-21 23:27 UTC, mtrpires commented
**Request to include r36s support to ports file**

[I've been trying to see](https://www.reddit.com/r/R36S/comments/1dlhgb4/goal_balatro_60fps_r36s/) whether Balatro can run at 60fps on my r36s and, thus far, have not been able to confirm it. I've tried editing some of the settings here and there, but I'm not sure I'm doing it right. 

I'd like to request adding support for the r36s and I could do it myself, but I would need guidance.