Added Super Meat Boy port
PortsMaster/PortMaster-New pull request #227
Opened 2024-03-25 22:28 UTC by fexofenadine

# New Port for Super Meat Boy

## Game Information
- **Title**: Super Meat Boy
- **URL**: [(https://store.steampowered.com/app/40800/Super_Meat_Boy/)]

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

2024-03-26 03:02 UTC, fexofenadine commented
currently testing in [Discord: Testing-n-Dev - SMB thread](https://discord.com/channels/1122861252088172575/1202446614992650280)

2024-04-02 10:24 UTC, fexofenadine commented
Updated with current test build

2024-04-07 02:11 UTC, kloptops commented on screenshot.jpg
Just need to delete this file. 😁

2024-04-07 02:15 UTC, kloptops requested changes
Just need to delete the screenshot at the root of the repo.

2024-04-07 04:36 UTC, fexofenadine reviewed
done!

2024-04-07 04:55 UTC, kloptops approved these changes
👍

2024-04-08 00:55 UTC, tabreturn approved these changes

2024-04-08 01:22 UTC, merged