Add issue templates
PortsMaster/PortMaster-New pull request #24
Opened 2024-02-01 18:13 UTC by JeodC

Adds two issue templates, one for the PortMaster GUI Tool and the other for specific Ports.

2024-02-01 20:35 UTC, Cebion requested changes
Maybe Replace RG353 with RG351MP.
Also add theRA firmware.

Device support list is vastly incomplete atm.

2024-02-02 01:10 UTC, kloptops requested changes
Could the gui template have a section requesting the pugwash.txt file.

2024-02-02 01:19 UTC, kloptops approved these changes
That’ll do. 😁

2024-02-02 07:31 UTC, Cebion approved these changes

2024-02-02 07:31 UTC, merged