New Port: Endless Dungeon
PortsMaster/PortMaster-New pull request #263
Opened 2024-04-04 17:20 UTC by mxmgorin

# New Port for Endless Dungeon

## Game Information
- **Title**: Endless Dungeon
- **URL**: [{ Link to project page or source control page }](https://randomnovice.itch.io/endless-dungeon)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [-] 480x320 (Not Lowres: Excluded)
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-04-04 19:42 UTC, Cebion requested changes
The sh does not have to be the same  name as the folder.
Some systems don't have Frontend names so we try to make the .sh with a real name So Endless Dungeon.sh

2024-04-04 20:11 UTC, mxmgorin commented
Fixed .sh name in the port.json

2024-04-05 08:54 UTC, Cebion approved these changes
👍

2024-04-06 05:27 UTC, kloptops approved these changes

2024-04-06 05:27 UTC, merged