Added Panzer Paladin port.
PortsMaster/PortMaster-New pull request #270
Opened 2024-04-08 03:18 UTC by JohnnyonFlame

# New Port for Panzer Paladin

## Game Information
- **Title**: Panzer Paladin
- **URL**: https://github.com/JohnnyonFlame/FNAPatches

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [ ] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [ ] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

2024-04-08 04:14 UTC, kloptops requested changes
Just the wrong version in the port.json

2024-04-08 04:14 UTC, kloptops commented on ports/panzerpaladin/port.json
> +    "version": 1,
This should be: `"version": 2,`

2024-04-08 08:00 UTC, JohnnyonFlame commented
I have defeated the workflow.

2024-04-09 02:14 UTC, JohnnyonFlame commented
Also fine on Batocera.

2024-04-09 07:13 UTC, Cebion approved these changes

2024-04-09 08:41 UTC, kloptops approved these changes
👍

2024-04-09 08:42 UTC, merged