New Port: SuDokul
PortsMaster/PortMaster-New pull request #273
Opened 2024-04-09 00:27 UTC by christopher-roelofs

# New Port for SuDokul

## Game Information
- **Title**: SuDokul
- **URL**: https://github.com/Mode8fx/SuDokuL

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-04-09 07:06 UTC, Cebion requested changes
We use a new header now

``` 
#!/bin/bash

XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi
```

2024-04-11 20:52 UTC, christopher-roelofs commented
> We use a new header now
> 
> ```
> #!/bin/bash
> 
> XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
> 
> if [ -d "/opt/system/Tools/PortMaster/" ]; then
>   controlfolder="/opt/system/Tools/PortMaster"
> elif [ -d "/opt/tools/PortMaster/" ]; then
>   controlfolder="/opt/tools/PortMaster"
> elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
>   controlfolder="$XDG_DATA_HOME/PortMaster"
> else
>   controlfolder="/roms/ports/PortMaster"
> fi
> ```

Done

2024-04-12 12:13 UTC, kloptops approved these changes
👍

2024-04-12 12:16 UTC, Cebion approved these changes

2024-04-12 12:16 UTC, merged