New Ports: arkovs tower
PortsMaster/PortMaster-New pull request #313
Opened 2024-04-22 10:19 UTC by mxmgorin

# New Port for Arkovs Tower

## Game Information
- **Title**: Arkovs Tower
- **URL**: https://store.steampowered.com/app/2688600/Descent_from_Arkovs_tower_Prologue/

## Submission Requirements

### Architecture Tests
[X] aarch64
[X] Panfrost (Mainline) 

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [X] ArkOS
- [X] JELOS
- [X] ROCKNIX
- [X] TrimUI

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-04-23 20:31 UTC, Cebion approved these changes

2024-04-24 13:12 UTC, kloptops requested changes
Delete the `.idea/` file and it should be good to go. 👍

2024-04-24 13:12 UTC, kloptops commented on .idea/.idea.PortMaster-New.dir/.idea/shelf/Uncommitted_changes_before_Update_at_4_22_2024_12_56_PM__local_.xml
Uhhhh, this file shouldn't be commit.

2024-04-24 13:18 UTC, mxmgorin commented
> Delete the `.idea/` file and it should be good to go. 👍

done

2024-04-24 13:28 UTC, merged