Drinkndrive
PortsMaster/PortMaster-New pull request #318
Opened 2024-04-23 23:45 UTC by MadShmupper

# New Port for { Drink'n'Drive }

## Game Information
- **Title**: { Drink'n'Drive }
- **URL**: { turboware.itch.io/drinkndrive }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-04-24 01:15 UTC, Slayer366 approved these changes

2024-04-24 13:00 UTC, Cebion requested changes
README.md credits for the original author are missing.
https://portmaster.games/packaging.html#readme-md

```Please always add a dedicated thank you note for the developer/creator. Without these people we would not be here.```


Gameinfo.xml has a space too much.

<path>.  /Drink'n'Drive.sh</path>
 
 vs 
 
  <path>. /Drink'n'Drive.sh</path>

2024-04-24 13:29 UTC, Cebion approved these changes

2024-04-25 07:09 UTC, kloptops approved these changes
👍

2024-04-25 07:10 UTC, merged