Added portfiles for Demonstone64
PortsMaster/PortMaster-New pull request #347
Opened 2024-05-01 05:07 UTC by MadShmupper

# New Port for { Demonstone64 }

## Game Information
- **Title**: { Demonstone64 }
- **URL**: { https://radcodex.itch.io/demonstone64 }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-01 21:48 UTC, Slayer366 commented on ports/demonstone64/README.md
> +Place Demonston.pck inside the gamedata folder
Change to:
```suggestion
Place Demonstone64.pck inside the gamedata folder
```

2024-05-02 01:13 UTC, Slayer366 requested changes
Add demonstone64/gamedata/place_Demonstone64_pck_here.txt

2024-05-02 02:00 UTC, Slayer366 approved these changes

2024-05-02 06:54 UTC, Cebion approved these changes

2024-05-02 06:54 UTC, merged