Add new port R&Watch-Dobtopus
PortsMaster/PortMaster-New pull request #355
Opened 2024-05-02 21:33 UTC by MadShmupper

# New Port for { R&Watch-Dobtopus }

## Game Information
- **Title**: { R&Watch-Dobtopus }
- **URL**: { https//:Nizakashii.itch.io/R&Watch }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-02 21:59 UTC, Cebion commented on ports/rwatch/port.json
Port.json wrong

foldername and zip name need to be the same name. Also .zip is missing

2024-05-02 21:59 UTC, Cebion commented on ports/rwatch/port.json
The port.json is also from a installed setup

2024-05-02 22:01 UTC, Cebion commented on ports/rwatch/README.md
The url to the game has to be a proper Internet link so https://url not @username

2024-05-02 22:02 UTC, Cebion requested changes
See comments

2024-05-02 22:44 UTC, Slayer366 requested changes

2024-05-02 22:44 UTC, Slayer366 commented on ports/rwatch/README.md
> +-Extract and place data.win file into gamedata folder
Like this:
```suggestion
Huge thank you to the creator of this game, nizakashii@itch.io, and thanks to all who tested and reviewed this port.
-Download from [Nizakashii] (https://nizakashii.itch.io/rwatch)
-Extract and place data.win file into gamedata folder
```

2024-05-02 22:59 UTC, Slayer366 requested changes

2024-05-02 22:59 UTC, Slayer366 commented on ports/rwatch/port.json
> +    "inst": "-Download at (https//:nizakashii.itch.io/R&Watch\n-Extract and place data.win into gamedata folder",
Missing a closing parentheses ')' after the internet link

2024-05-03 07:48 UTC, Cebion commented
One last question
"porter": [
      "MadShmupper",
      "Jeod",
      "JanTrueno"
    ],
Did really all 3 work actively on the port and can answer questions about the port?
Or did one just help test or zip it up
Because they will be asked if anything is wrong iwth the port in the future
Else they'll just get a thank you note on the readme

2024-05-04 11:37 UTC, Cebion approved these changes

2024-05-06 09:04 UTC, kloptops approved these changes
👍

2024-05-06 09:04 UTC, merged