Lisa the unbreakable port
PortsMaster/PortMaster-New pull request #367
Opened 2024-05-06 13:18 UTC by Tlaggypyro

# New Port for { Lisa The Unbreakable }

## Game Information
- **Title**: { Lisa The Unbreakable }
- **URL**: { https://gamejolt.com/games/lisa-the-unbreakable/440612 }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-07 07:50 UTC, Cebion requested changes

2024-05-07 07:50 UTC, Cebion commented on ports/lisatheunbreakable/Screenshot.jpg
Screenshot needs to be 640x480 and needs to be named screenshot.jpg

2024-05-07 07:50 UTC, Cebion commented on ports/lisatheunbreakable/gameinfo.xml
Please fill the gameinfo xml (https://portmaster.games/metadata-editor.html)

2024-05-08 08:38 UTC, Cebion approved these changes

2024-05-08 09:06 UTC, kloptops approved these changes
👍

2024-05-08 09:06 UTC, merged