New Port Forgodden
PortsMaster/PortMaster-New pull request #380
Opened 2024-05-10 01:45 UTC by Fraxinus88

# New Port for Forgodden

## Game Information
- **Title**: Forgodden
- **URL**: https://gizmo199.itch.io/forgodden OR https://github.com/Gizmo199/Forgodden

## Submission Requirements

## CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] JELOS 
[X] ROCKNIX

Architecture
[X] armHF
[X] Panfrost (Mainline) 

Resolution Tests
Test all major resolutions:
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720) 

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-11 05:25 UTC, kloptops requested changes
just need the port.json fixed.

2024-05-11 05:25 UTC, kloptops commented on ports/forgodden/port.json
> +  "version": 3,
version should be 2?

2024-05-12 06:40 UTC, kloptops approved these changes
👍

2024-05-12 12:19 UTC, Cebion approved these changes

2024-05-12 12:19 UTC, merged