New Port Mythos
PortsMaster/PortMaster-New pull request #381
Opened 2024-05-10 07:46 UTC by Fraxinus88

# New Port for Mythos

## Game Information
- **Title**: Mythos
- **URL**: https://alkaliii.itch.io/mtgl

## Submission Requirements

CFW Tests:
[X] AmberELEC
[X] ArkOS
[ ] JELOS 
[X] ROCKNIX

Architecture
[X] armHF
[X Panfrost (Mainline) 

Resolution Tests
Test all major resolutions:
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-11 05:28 UTC, kloptops requested changes
Looks good otherwise?

2024-05-11 05:28 UTC, kloptops commented on ports/mythos/mythos/LICENSE.GAME.txt
Is this file meant to be included with this port?

2024-05-11 05:28 UTC, kloptops commented on ports/mythos/port.json
> +  "version": 3,
version 3?

2024-05-11 15:34 UTC, Fraxinus88 commented on ports/mythos/mythos/LICENSE.GAME.txt
Yes, got a tentative approval, have included it as the LICENSE.aiwi.txt

2024-05-12 06:42 UTC, kloptops requested changes

2024-05-12 06:42 UTC, kloptops commented on ports/mythos/mythos/LICENSE.GAME.txt
Yeah but the LICENSE.GAME.txt is for bananamanguy?

2024-05-12 12:18 UTC, Cebion approved these changes

2024-05-12 12:18 UTC, merged