Lisa the Timeless port
PortsMaster/PortMaster-New pull request #383
Opened 2024-05-10 13:40 UTC by Tlaggypyro

# New Port for {Lisa the Timeless }

## Game Information
- **Title**: { Lisa The Timeless }
- **URL**: {https://gamejolt.com/games/LISA-The-Timeless/629435}

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-11 05:32 UTC, kloptops submitted a review, later dismissed
Looks good 👍

2024-05-12 12:16 UTC, Cebion requested changes

2024-05-12 12:16 UTC, Cebion commented on ports/lisathetimeless/gameinfo.xml
Please fill out basic info in the gameinfo.xml

2024-05-12 12:16 UTC, Cebion commented on ports/lisathetimeless/port.json
> +        "lisatheTimeless"
foldernames need to be complety lowercase
"lisatheTimeless"

vs 
""lisathetimeless"

2024-05-12 19:57 UTC, Cebion approved these changes

2024-05-13 11:46 UTC, kloptops approved these changes

2024-05-13 11:46 UTC, merged