Add New Port OverGun
PortsMaster/PortMaster-New pull request #437
Opened 2024-05-27 18:36 UTC by MadShmupper

# New Port for { OverGun }

## Game Information
- **Title**: { OverGun }
- **URL**: { https://yousfiwalid.itch.io/over-gun }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [ ] ArkOS
- [ ] ROCKNIX
- [ ] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-05-28 11:00 UTC, kloptops submitted a review, later dismissed

2024-05-28 11:10 UTC, Cebion requested changes
See comments

2024-05-28 11:10 UTC, Cebion commented on ports/overgun/gameinfo.xml
> +    <image>./overGun/cover.png</image>
<image> tag folderpath is wrong. Needs to match the folder (linux is case sensitive)

2024-05-28 11:10 UTC, Cebion commented on ports/overgun/overgun/overgun.gptk
> +a = cntrl
There is no keyboard key called "cntrl" only "ctrl"

2024-05-28 21:37 UTC, kloptops approved these changes

2024-05-29 07:43 UTC, Cebion approved these changes

2024-05-29 07:43 UTC, merged

2024-05-29 14:54 UTC, MadShmupper commented
👾👾👾
       : 
   🚀