New Port Rebound
PortsMaster/PortMaster-New pull request #443
Opened 2024-05-31 18:08 UTC by Tlaggypyro

# New Port for { Rebound }

## Game Information
- **Title**: { Rebound }
- **URL**: { https://rebound.itch.io/rebound }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-02 19:32 UTC, Cebion requested changes

2024-06-02 19:32 UTC, Cebion commented on ports/rebound/screenshot.jpg
Screenshot needs to be not squashed and 640x480 in resolution.
You can take screenshots on your device via https://portmaster.games/port-tools.html#capture-video-and-screenshots for example

2024-06-03 00:56 UTC, kloptops commented on ports/rebound/Rebound.sh
> +exec > >(tee "$GAMEDIR/log.txt") 2>&1
Old logging style, use this instead: `> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1`

2024-06-03 00:57 UTC, kloptops commented on ports/rebound/port.json
> +        "title": "Brad Has A Pain",
Is the game named rebound, or brad had a pain?

2024-06-03 00:58 UTC, kloptops requested changes
Just need fixes on the `port.json` and `Rebound.sh`

2024-06-05 14:45 UTC, Cebion approved these changes

2024-06-05 14:45 UTC, merged