New Port Luminous Slash
PortsMaster/PortMaster-New pull request #444
Opened 2024-06-02 02:37 UTC by Fraxinus88

# New Port for Luminous Slash

## Game Information
- **Title**: Luminous Slash
- **URL**: https://gizmo199.itch.io/luminous-slash

## Submission Requirements
**CFW Tests:**
[X] AmberELEC
[X] ArkOS
[X] JELOS/ROCKNIX
[X] MuOS

**Architecture**
[X] armHF
[X] Panfrost (Mainline)

**Resolution Tests**
Test all major resolutions:
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-02 19:35 UTC, Cebion requested changes

2024-06-02 19:35 UTC, Cebion commented on ports/luminousslash/Luminous Slash.sh
> +if [ -d "/opt/system/Tools/PortMaster/" ]; then
Old Port Header

2024-06-02 19:35 UTC, Cebion commented on ports/luminousslash/screenshot.png
Screenshot should be 640x480.
You can take screenshots on your device for example with https://portmaster.games/port-tools.html#capture-video-and-screenshots

2024-06-05 14:36 UTC, Fraxinus88 commented on ports/luminousslash/screenshot.png
Updated :)

2024-06-05 14:43 UTC, Cebion approved these changes

2024-06-06 10:46 UTC, kloptops approved these changes
👍

2024-06-06 10:46 UTC, merged