Update Chip 'n' Dale
PortsMaster/PortMaster-New pull request #446
Opened 2024-06-06 23:57 UTC by Slayer366

Update Chip 'n' Dale RRR
-Clean up and update shell script.
-Update port.json
-Fix controls not working on some configurations/systems

2024-06-07 07:18 UTC, Cebion submitted a review, later dismissed

2024-06-09 00:56 UTC, kloptops requested changes
Looks good other than the json file needs a fix.

2024-06-09 00:56 UTC, kloptops commented on ports/chipndale/port.json
>              "Tekkenfede"
Missing comma.

2024-06-09 05:02 UTC, kloptops approved these changes

2024-06-09 05:03 UTC, merged