Add New Port Spacewing War
PortsMaster/PortMaster-New pull request #448
Opened 2024-06-08 02:11 UTC by MadShmupper

# New Port for { Spacewing War }

## Game Information
- **Title**: { Spacewing War }
- **URL**: { https://store.steampowered.com/app/1979470/Spacewing_War/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-09 01:00 UTC, kloptops approved these changes
👍

2024-06-09 06:32 UTC, MadShmupper commented
Kloptops & Cebion, I goofed up and pr'd this one before I had all resolutions by mistake. While I've no reason to believe it won't work on higher res, I'm still awaiting a high res test. Sorry for the hiccup fellas. 👾🤖👽

2024-06-10 03:48 UTC, MadShmupper commented
Okay, Cebion.. This one is officially ready now. All tests in🙂

2024-06-11 15:16 UTC, Cebion requested changes

2024-06-11 15:16 UTC, Cebion commented on ports/spacewingwar/gameinfo.xml
> +    <image>./spacewing War/cover.png</image>
foldername wrong

2024-06-12 12:00 UTC, Slayer366 requested changes

2024-06-12 22:56 UTC, Slayer366 approved these changes
Lookin' good!

2024-06-13 02:24 UTC, MadShmupper commented
> Lookin' good!

Thank ya kindly for the help👾

2024-06-13 17:19 UTC, MadShmupper commented on ports/spacewingwar/gameinfo.xml
> +    <image>./spacewing War/cover.png</image>
Fixed🙂

2024-06-13 17:19 UTC, MadShmupper commented on ports/spacewingwar/Spacewing War.sh
> +fi
Fixed this.

2024-06-13 18:22 UTC, Cebion approved these changes

2024-06-15 17:36 UTC, merged

2024-06-15 19:08 UTC, MadShmupper commented
😎