New Port: Lineoff
PortsMaster/PortMaster-New pull request #463
Opened 2024-06-14 10:29 UTC by JanTrueno

# New Port for Lineoff

## Game Information
- **Title**: Lineoff
- **URL**: https://kultisti.itch.io/lineoff

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-15 12:53 UTC, Cebion requested changes

2024-06-15 12:53 UTC, Cebion commented on ports/lineoff/README.md
> +Special thanks to [Kultisti](https://kultisti.itch.io/curseball) for creating the game and allowing us to distribute the files! Check out the games page [here](https://kultisti.itch.io/lineoff).
Credit links goes to another game

2024-06-16 10:38 UTC, kloptops approved these changes
👍

2024-06-16 18:02 UTC, Slayer366 approved these changes

2024-06-18 09:29 UTC, merged