New Port Lisa The Bashful
PortsMaster/PortMaster-New pull request #467
Opened 2024-06-15 18:21 UTC by Tlaggypyro

# New Port for { Lisa the Bashful }

## Game Information
- **Title**: { Lisa The Bashful }
- **URL**: {https://gamejolt.com/games/Lisathebashful/430290 }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-16 07:17 UTC, kloptops requested changes
Just need the port.json changed.

2024-06-16 07:17 UTC, kloptops commented on ports/lisathebashful/port.json
> +    "status": {
The "status" and "files" tags shouldn't be included.

2024-06-18 09:32 UTC, kloptops requested changes
Just need to change the logging line in the bash script.

2024-06-18 09:32 UTC, kloptops commented on ports/lisathebashful/LISA The Bashful.sh
> +exec > >(tee "$GAMEDIR/log.txt") 2>&1
Outdated logging directive, use `> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1`

2024-06-18 13:22 UTC, Cebion approved these changes

2024-06-19 11:38 UTC, kloptops approved these changes

2024-06-19 11:38 UTC, merged