Add New Port Z-Warp
PortsMaster/PortMaster-New pull request #470
Opened 2024-06-15 22:55 UTC by MadShmupper

# New Port for { Z-Warp }

## Game Information
- **Title**: { Z-Warp }
- **URL**: { https://store.steampowered.com/app/1990820/ZWARP/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-16 06:33 UTC, kloptops submitted a review, later dismissed
👍

2024-06-16 19:07 UTC, Slayer366 approved these changes

2024-06-17 20:11 UTC, Slayer366 requested changes

2024-06-17 20:11 UTC, Slayer366 commented on ports/z-warp/Z-Warp.sh
> +> "$ GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
```suggestion
> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
```

2024-06-17 21:43 UTC, MadShmupper commented on ports/z-warp/Z-Warp.sh
> +> "$ GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
Done🙂

2024-06-18 00:25 UTC, Slayer366 approved these changes

2024-06-18 09:41 UTC, kloptops approved these changes

2024-06-18 09:41 UTC, merged