New Port: Dark Sheep
PortsMaster/PortMaster-New pull request #473
Opened 2024-06-16 13:37 UTC by mhoogcarspel

# New Port for Dark Sheep

## Game Information
- **Title**: Dark Sheep
- **URL**: https://daisy-games.itch.io/dark-sheep

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [ ] muOS
- [X] KNULLI

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

2024-06-17 20:29 UTC, Slayer366 requested changes

2024-06-17 20:29 UTC, Slayer366 commented on ports/darksheep/Dark Sheep.sh
> +cd $GAMEDIR
The script already enters the game directory at line 26.  While harmless, it only needs to do this once.
```suggestion
```

2024-06-17 20:29 UTC, Slayer366 commented on ports/darksheep/darksheep/darksheep.gptk
> +y = "\
```suggestion
y = \"

```

2024-06-17 20:29 UTC, Slayer366 commented on ports/darksheep/darksheep/darksheep.gptk
> +l1 = "\
```suggestion
l1 = \"

```

2024-06-17 20:29 UTC, Slayer366 commented on ports/darksheep/darksheep/darksheep.gptk
> +r2 = "\
```suggestion
r1 = \"
r2 = \"

```

2024-06-17 20:29 UTC, Slayer366 commented on ports/darksheep/darksheep/darksheep.gptk
> +right_analog_right = "\
```suggestion
right_analog_up = \"
right_analog_down = \"
right_analog_left = \"
right_analog_right = \"
```

2024-06-17 21:29 UTC, Slayer366 requested changes

2024-06-17 21:29 UTC, Slayer366 commented on ports/darksheep/port.json
> +    "inst": "Grab the windows version from https://daisy-games.itch.io/dark-sheep\nand copy DarkSheep.pck into /roms/ports/darksheep/gamedata\n\nText is harder to read on 320p, but playable. Works be
muOS has the ports placed in the ports folder at the root which in turn mounts as /mnt/mmc/ports for the 1st memory stick or /mnt/sdcard/ports for the 2nd memory stick so /roms/ports (which could also be /roms2/ports for the 2nd memory stick on ArkOS, for example) isn't absolute.
```suggestion
    "inst": "Grab the windows version from https://daisy-games.itch.io/dark-sheep\nand copy DarkSheep.pck into ports/darksheep/gamedata\n\nText is harder to read on 320p, but playable. Works best on 480p and up.",
```

2024-06-18 12:15 UTC, mhoogcarspel commented
Thanks for the second pair of eyes Slayer!

2024-06-18 12:50 UTC, Slayer366 approved these changes

2024-06-18 13:18 UTC, merged