Add New Port Pepper Pengui
PortsMaster/PortMaster-New pull request #477
Opened 2024-06-18 23:55 UTC by MadShmupper

# New Port for { Pepper Pengui }

## Game Information
- **Title**: { Pepper Pengui }
- **URL**: { https://redscreensoft.com/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-19 12:24 UTC, kloptops approved these changes

2024-06-21 05:42 UTC, Slayer366 approved these changes

2024-06-21 08:32 UTC, Cebion requested changes

2024-06-21 08:32 UTC, Cebion commented on ports/ppengui/README.md
> +
Game source URL is missing

2024-06-21 08:32 UTC, Cebion commented on ports/ppengui/cover.png
Title Screenshots are not allowed for cover.
Either Screenshots or screenshots with inlay logo / titles

2024-06-23 20:52 UTC, merged