Add New Port Crystals of Amalgam
PortsMaster/PortMaster-New pull request #478
Opened 2024-06-19 00:26 UTC by MadShmupper

# New Port for { Crystals of Amalgam }

## Game Information
- **Title**: { Crystals of Amalgam }
- **URL**: { https://redscreensoft.com/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-19 12:25 UTC, kloptops submitted a review, later dismissed
👍

2024-06-21 08:31 UTC, Cebion requested changes

2024-06-21 08:31 UTC, Cebion commented on ports/crystalsamalgam/cover.png
title images for covers with just text are not allowed.
Either screenshot or screenshot with inlay logo

2024-06-21 19:37 UTC, MadShmupper commented on ports/crystalsamalgam/README.md
> +
Thank you. I shall fix all these this evening.

2024-06-23 20:50 UTC, Cebion approved these changes

2024-06-23 20:50 UTC, merged