New Port Breaker
PortsMaster/PortMaster-New pull request #479
Opened 2024-06-19 11:16 UTC by Fraxinus88

# New Port for Breaker

## Game Information
- **Title**: Breaker
- **URL**: https://managore.itch.io/breaker

## Submission Requirements
CFW's:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS

Architectures:
[X] armhf
[X] Panfrost (Mainline)

Resolutions:
Test all major resolutions:
[X] 480x320 (optional)
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-19 12:29 UTC, kloptops submitted a review, later dismissed
👍

2024-06-21 08:29 UTC, Cebion requested changes

2024-06-21 08:29 UTC, Cebion commented on ports/breaker/gameinfo.xml
> +    <path>,/Breaker.sh</path>
typo

2024-06-21 13:49 UTC, Fraxinus88 commented on ports/breaker/gameinfo.xml
> +    <path>,/Breaker.sh</path>
whoopsies

2024-06-23 20:48 UTC, Cebion approved these changes

2024-06-23 20:48 UTC, merged