New port Red Trees
PortsMaster/PortMaster-New pull request #480
Opened 2024-06-19 14:02 UTC by Tlaggypyro

# New Port for { Red Trees }

## Game Information
- **Title**: { Red Trees }
- **URL**: { https://caramel.itch.io/redtrees }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-20 08:33 UTC, kloptops commented on ports/redtrees/Red Trees.sh
> +exec > >(tee "$GAMEDIR/log.txt") 2>&1
Need to replace the logging code with the new standard way.

```suggestion
> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
```

2024-06-20 08:34 UTC, kloptops requested changes
Just need the logging fix. :)

2024-06-21 08:28 UTC, Cebion approved these changes

2024-06-21 10:28 UTC, kloptops approved these changes
👍

2024-06-21 10:28 UTC, merged