Add New Port Streets of Claus
PortsMaster/PortMaster-New pull request #481
Opened 2024-06-19 22:05 UTC by MadShmupper

# New Port for { Streets of Claus }

## Game Information
- **Title**: { Streets of Claus }
- **URL**: { https://redscreensoft.com/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-20 08:38 UTC, kloptops requested changes
Just the port.json changes today. 😄

2024-06-20 19:41 UTC, MadShmupper commented on ports/streetsofclaus/port.json
> +    "status": {
Done. Thank you 👾

2024-06-21 08:26 UTC, Cebion requested changes

2024-06-21 08:26 UTC, Cebion commented on ports/streetsofclaus/README.md
> +
Missing source to the game page

2024-06-21 08:26 UTC, Cebion commented on ports/streetsofclaus/cover.png
The cover is two squided screenshots together.
Please do either a screenshot or screenshot with overlay cover.

2024-06-21 10:29 UTC, kloptops submitted a review, later dismissed
👍

2024-06-25 11:11 UTC, kloptops approved these changes
👍

2024-06-25 11:26 UTC, Cebion approved these changes

2024-06-25 11:26 UTC, merged