Battalion
PortsMaster/PortMaster-New pull request #486
Opened 2024-06-24 20:48 UTC by MadShmupper

Add New Port Battalion

# New Port for { Battalion }

## Game Information
- **Title**: { Battalion }
- **URL**: { https://all-x.itch.io/battalion }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-24 23:11 UTC, Slayer366 requested changes

2024-06-24 23:11 UTC, Slayer366 commented on ports/battalion/gameinfo.xml
> +    <path>./BATTALION.sh</path>
```suggestion
    <path>./Battalion.sh</path>
```

2024-06-24 23:11 UTC, Slayer366 commented on ports/battalion/port.json
> +        "BATTALION.sh",
```suggestion
        "Battalion.sh",
```
Your shell script is not in all caps.  You can change the shell script to be in all caps or you'll need to change the entries in your gameinfo.xml and port.json as per my suggestions to match the shell script name especially with case sensitivity.

2024-06-24 23:11 UTC, Slayer366 commented on ports/battalion/port.json
> +    "status": {
You have these entries created by harbourmaster in your port.json
```suggestion
    "status": {
```

2024-06-24 23:11 UTC, Slayer366 commented on ports/battalion/port.json
> +    "files": {
You have these entries created by harbourmaster in your port.json
```suggestion
    "files": {
```

2024-06-25 11:16 UTC, kloptops approved these changes
👍

2024-06-25 11:31 UTC, Cebion approved these changes

2024-06-25 11:31 UTC, merged