New Port: FreeSiege
PortsMaster/PortMaster-New pull request #489
Opened 2024-06-27 12:27 UTC by Cebion

Game Information
Title: FreeSiege
URL: https://freesiege.sourceforge.net/

Suggestion 
https://suggestions.portmaster.games/suggestion-details?id=28822655a2654db19f8f9d405906005c

Instructions: 
Ready to run

Controls:
| Button | Action |
|--|--| 
|DPAD| Move |
|A| Switch Tiles |
|B| Activate Tiles |

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X]  ROCKNIX
[X] muOS 

Architecture
[X] aarch64
[X] Panfrost (Mainline) 

Resolution Tests
Test all major resolutions:
[X] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

2024-06-27 23:16 UTC, Slayer366 requested changes

2024-06-27 23:16 UTC, Slayer366 commented on ports/freesiege/freesiege/xcf/gif_to_bmp.sh
If this shell script isn't needed by the game, it could probably be renamed or removed so that it doesn't make the folder(s) show up in the Ports list

2024-06-27 23:16 UTC, Slayer366 commented on ports/freesiege/FreeSiege.sh
> +export LD_LIBRARY_PATH="$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
While harmless, I don't see a libs.aarch64 directory, so this line might not be needed (?)

2024-06-28 06:20 UTC, Cebion commented on ports/freesiege/freesiege/xcf/gif_to_bmp.sh
Good catch!

2024-06-28 06:23 UTC, merged