Adding Render96ex port
PortsMaster/PortMaster-New pull request #493
Opened 2024-06-27 17:48 UTC by cdeletre

# New Port for Render96ex

## Game Information
- **Title**: Render96ex
- **URL**: https://github.com/Render96/Render96ex

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS (with limitation)

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [X] 640x480
- [] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-06-27 19:39 UTC, cdeletre commented
I forgot to add back the `.gitignore` (generated by `build_data.py`) after restructuring the port and playing with git. I fixed this in this commit https://github.com/cdeletre/PortMaster-New/commit/be7cc498c80a409a6dfe86cf6cfe79bc9bc8ddbc

Sorry guys !

2024-06-28 06:32 UTC, Cebion requested changes

2024-06-28 06:32 UTC, Cebion commented on ports/render96ex/render96ex.sh
> +export DEVICE_ARCH="${DEVICE_ARCH:-aarch64}"
Since we longer deal with multiarch on armhf this line is not needed anymore.

2024-06-28 06:32 UTC, Cebion commented on ports/render96ex/render96ex.sh
> +# PORTMASTER: sm64.zip, sm64.sh
This line is autogenerated by Portmaster

2024-06-28 06:32 UTC, Cebion commented on ports/render96ex/render96ex.sh
> +XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
Header should always be on top =)

2024-06-28 06:32 UTC, Cebion commented on ports/render96ex/render96ex.sh
> +# We source custom mod files from the portmaster folder example mod_jelos.txt which containts pipewire fixes
Comments are nice for explanations how the .sh works but in the release version we usually keep them to a minimum. 
See https://portmaster.games/packaging.html#basic-launchscript for an example.

2024-06-28 06:32 UTC, Cebion commented on ports/render96ex/render96ex.sh
> +if [ -f "${controlfolder}/libgl_${CFW_NAME}.txt" ]; then
this game does not use gl4es as it seems. So this whole libgl part is not needed.

2024-06-28 14:10 UTC, cdeletre commented
Thank you for the feedback @Cebion ! I've fixed these issues in my last commit https://github.com/PortsMaster/PortMaster-New/pull/493/commits/edbc14c4ac9b2e7bf68b566bd140713c9ac95184

2024-06-29 11:51 UTC, Slayer366 requested changes

2024-06-29 11:51 UTC, Slayer366 commented on ports/render96ex/.gitignore
This .gitignore file could be deleted.  
Everything else looks good.

2024-06-29 11:52 UTC, Slayer366 approved these changes

2024-06-30 20:30 UTC, merged