Add new port: Descent 3
PortsMaster/PortMaster-New pull request #500
Opened 2024-06-30 07:16 UTC by JeodC

# New Port for Descent 3

## Game Information
- **Title**: Descent 3

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-06-30 18:24 UTC, Slayer366 requested changes

2024-06-30 18:24 UTC, Slayer366 commented on ports/descent3/gameinfo.xml
> +    <image>./descent/cover.png</image>
```suggestion
    <image>./descent3/cover.jpg</image>
```

2024-06-30 20:43 UTC, Cebion requested changes

2024-06-30 20:43 UTC, Cebion commented on ports/descent3/cover.jpg
Cover has to be the same format as the screenshots. 640x480.
Its not a literal cover from boxart but a screenshot with embedded logo for example.
This art is shown in emulationstation. A screenshot with mixed art is also okay. Like skraper v3 screenshots.

2024-06-30 20:44 UTC, JeodC commented on ports/descent3/cover.jpg
This is from skraper actually.

2024-07-01 05:15 UTC, Slayer366 requested changes

2024-07-01 05:15 UTC, Slayer366 commented on ports/descent3/gameinfo.xml
> +    <image>./descent3/cover.jpg</image>
Per Cebion's suggestion:
```suggestion
    <image>./descent3/screenshot.png</image>
```

2024-07-01 07:12 UTC, merged