New Ports: Sonic SMS Remakes
PortsMaster/PortMaster-New pull request #511
Opened 2024-07-05 09:28 UTC by JanTrueno

# New Port for Sonic SMS Remakes

## Game Information
- **Title**:  Sonic SMS Remakes}
- **URL**: https://sonic-sms-remake.blogspot.com/

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X ] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-07-05 11:22 UTC, Cebion submitted a review, later dismissed

2024-07-06 02:47 UTC, Slayer366 requested changes

2024-07-06 02:47 UTC, Slayer366 commented on ports/sonic1sms/Sonic 1 SMS Remake.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$GAMEDIR/utils/libs"
```suggestion
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
```
While harmless, there isn't a utils folder.

2024-07-06 02:47 UTC, Slayer366 commented on ports/sonic2sms/Sonic 2 SMS Remake.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$GAMEDIR/utils/libs"
```suggestion
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
```
While harmless, there isn't a utils folder.

2024-07-06 02:47 UTC, Slayer366 commented on ports/sonic3sms/Sonic 3 SMS Remake.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$GAMEDIR/utils/libs"
```suggestion
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
```
While harmless, there isn't a utils folder.

2024-07-07 07:45 UTC, kloptops approved these changes
Looks good. 👍

2024-07-07 16:25 UTC, Slayer366 approved these changes

2024-07-08 19:51 UTC, merged