New Port: mReader
PortsMaster/PortMaster-New pull request #514
Opened 2024-07-08 17:52 UTC by booYah187

Game Information
Title: mReader
URL: https://github.com/booYah187/mReader

Instructions: This port is ready to run.

Controls
| Button | Action |
||| 
|DPAD/LStick/RStick| Scroll/Page|
|A/L1/R2| Enter|
|B| Back|
|X| Settings|
|Y/Start| TOC|

CFW Tests
[X] AmberELEC
[X] ArkOS
[X] JELOS / ROCKNIX
[X] muOS 

Architecture
[X] aarch64
[X] Panfrost (Mainline) 

Resolution Tests
Test all major resolutions:
[] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

# New Port for { Game Title }

## Game Information
- **Title**: { Game Title }
- **URL**: { Link to project page or source control page }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [ ] ArkOS
- [ ] ROCKNIX
- [ ] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [ ] 640x480
- [ ] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-07-08 20:22 UTC, Cebion requested changes

2024-07-08 20:22 UTC, Cebion commented on ports/mreader/gameinfo.xml
> +    <developer>https://github.com/booYah187/mReader</developer>
Don't use  URL as developer name. Persons or Groups or unknown.

2024-07-08 20:22 UTC, Cebion commented on ports/mreader/gameinfo.xml
> +    <image>./mReader/cover.png</image>
foldername needs to be lowercase

2024-07-08 20:22 UTC, Cebion commented on ports/mreader/mreader/mReader.sh
You have two mReader.sh files.

2024-07-08 20:22 UTC, Cebion commented on ports/mreader/port.json
> +    "name": "mReader.zip",
zipname and folder name need to be lowercase

2024-07-08 20:22 UTC, Cebion commented on ports/mreader/port.json
> +        "mReader"
lowercase

2024-07-08 20:43 UTC, booYah187 commented on ports/mreader/port.json
> +        "mReader"
Corrections committed.

2024-07-08 20:51 UTC, Cebion approved these changes

2024-07-09 03:57 UTC, kloptops approved these changes
👍

2024-07-09 03:57 UTC, merged