Add New Port Riptale
PortsMaster/PortMaster-New pull request #531
Opened 2024-07-13 18:33 UTC by MadShmupper

# New Port for { Riptale }

## Game Information
- **Title**: { Riptale }
- **URL**: { https://store.steampowered.com/app/616000/Riptale/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-07-14 06:17 UTC, kloptops approved these changes
Looks good. 👍

2024-07-14 16:28 UTC, Cebion requested changes

2024-07-14 16:28 UTC, Cebion commented on ports/riptale/Riptale.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
LD_LIBRARY path is overwriting system library exports.

This part needs to go to the end
```:$LD_LIBRARY_PATH"```

So 

```
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$LD_LIBRARY_PATH"
```

2024-07-14 16:28 UTC, Cebion commented on ports/riptale/port.json
> +    "inst": "Purchase from Steam https://store.steampowered.com/app/616000/Riptale/ Using only the latest Steam or Windows version, locate game.unx/data.win, audiogroup1.dat & audiogroup2.dat, plus a
The inst field is only shown in the PortMaster app, has limited view for instructions. So putting full links in there might not b the best idea.

The inst_md field on the other hand is for the Instructions on the game details page where you can explain as long as you like. 

So on app make it short and snappy and on the website the full blown thing.

2024-07-14 17:01 UTC, Slayer366 requested changes

2024-07-14 17:01 UTC, Slayer366 commented on ports/riptale/Riptale.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
```suggestion
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$LD_LIBRARY_PATH"
```
Exactly as Cebion suggested, this is what we should have in the event that LD_LIBRARY_PATH already has a previously set value ^.  Admittedly, I should've caught this.

2024-07-14 17:13 UTC, Slayer366 approved these changes

2024-07-15 12:21 UTC, Cebion approved these changes

2024-07-15 12:21 UTC, merged