New port: Frozen Bubble
PortsMaster/PortMaster-New pull request #538
Opened 2024-07-15 12:42 UTC by cdeletre

# New Port for Frozen Bubble

## Game Information
- **Title**: Frozen Bubble
- **URL**: https://github.com/kthakore/frozen-bubble/

## Submission Requirements

### CFW Tests

- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests

- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure

```
.
├── README.md
├── cover.jpg
├── frozen-bubble
│   ├── data
│   ├── fb-server
│   ├── frozen-bubble
│   ├── frozen-bubble.GPL-2.0.LICENSE.txt
│   ├── frozen-bubble.gptk
│   ├── gfx.squashfs
│   ├── icons
│   ├── libs.aarch64
│   ├── locale
│   ├── perl.squashfs
│   └── snd
├── frozen-bubble.sh
├── gameinfo.xml
├── port.json
└── screenshot.jpg
```

## Controls

| Button | Action |
|--|--| 
|D-PAD left/right|aim left/right (P1)|
|D-PAD down|aim center  (P1)|
|D-PAD up|fire (P1)|
|L1|fire (P1)|
|L-Stick up|send malus to top left player (multiplayer only)|
|L-Stick down|send malus to bottom left player (multiplayer only)|
|R-Stick up|send malus to top right player (multiplayer only)|
|R-Stick down|send malus to bottom right player (multiplayer only)|
|R3|send malus to all opponents (multiplayer only)|
|Y/A|aim left/right (P2)|
|B|aim center (P2)|
|X|fire (P2)|
|R1|fire (P2)|
|Start|Enter|
|Select|Esc|
|L2|Y (yes)|
|R2|N (no)|
|L3|toggle music on/off|

2024-07-15 12:51 UTC, Cebion requested changes

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/README.md
Compile Instructions are missing in the README.md

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/cover.jpg
Cover should be 640x480 and show gameplay and or a gameplay / coverartmix or gameplay / logo artmix.

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/frozen-bubble.sh
> +# PORTMASTER: render96ex.zip, render96ex.sh
This line is autogenerated by PortMaster.  Can be removed
```suggestion

```

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/frozen-bubble/libs.aarch64/amberelec_ldd.txt
Is this file necessary?

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/gameinfo.xml
> +    <path>./frozen-bubble.sh</path>
.sh Name needs to be Uppercase. This is the Name that is shown when no Metadata is used.

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/port.json
> +    "frozen-bubble.sh",
.sh needs to be Upper Case

2024-07-15 12:51 UTC, Cebion commented on ports/frozen-bubble/screenshot.jpg
this is already perfect for cover. So use screenshot.jpg in the gameinfo.xml instead of cover.jpg

2024-07-15 19:33 UTC, cdeletre commented on ports/frozen-bubble/frozen-bubble/libs.aarch64/amberelec_ldd.txt
Indeed, it's useless now :)

2024-07-15 21:20 UTC, cdeletre commented
New commit :)

2024-07-16 07:48 UTC, Cebion approved these changes

2024-07-16 07:48 UTC, merged