Fix various scripts to use modern standards and add :$LD_LIBRARY_PATH…
PortsMaster/PortMaster-New pull request #540
Opened 2024-07-16 16:37 UTC by Cebion

…" to ld_library_path exports for tsp & rocknix compatiblity

Important that in the future we make sure to add :$LD_LIBRARY_PATH" in the ld_library_path

2024-07-17 11:18 UTC, kloptops requested changes
Damn boi.

2024-07-17 11:18 UTC, kloptops commented on ports/shovel.knight/Shovel Knight.sh
> -
What? 🐢

2024-07-17 11:18 UTC, kloptops commented on ports/sonic.cd/Sonic CD.sh
>    export LD_LIBRARY_PATH="$GAMEDIR/libs:/usr/lib:/usr/lib32"
Did you miss this?

2024-07-17 17:38 UTC, Cebion commented on ports/moonlight/Moonlight.sh
Because no exceptions

2024-07-18 09:48 UTC, kloptops requested changes

2024-07-18 09:48 UTC, kloptops commented on ports/shovel.knight/Shovel Knight.sh
> -
So you're going to update the port for no reason? 😁

2024-07-18 09:48 UTC, kloptops commented on ports/moonlight/Moonlight.sh
This gives users a false sense that the port is updated. You should just change the port.json so that is ArkOS only and renamed it "Moonlight Old". 😁

2024-07-18 21:19 UTC, kloptops requested changes

2024-07-18 21:19 UTC, kloptops commented on ports/moonlight/port.json
> +        "reqs": [arkos],
Missing double quotes around `"arkos"`:
```suggestion
        "reqs": ["arkos"],
```

2024-07-18 22:16 UTC, kloptops approved these changes

2024-07-18 22:16 UTC, merged

2024-07-25 15:20 UTC, JeodC commented on ports/alchemyquest/Alchemy Quest.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/cosmo-engine/Cosmos Cosmic Adventure.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/davegnukem/Dave Gnukem.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/enigma/Enigma.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/f1race/F1 Race.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/freegemas/Freegemas.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/heboris-sdl/Heboris-sdl.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/hota/Heart Of The Alien Redux.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/hoverboard/xkcd Hoverboard.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/kobodeluxe/Kobo Deluxe.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/laserkombat/Laser Kombat.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/meandmyshadow/Me and My Shadow.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/mirrormagic/Mirror Magic.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/missdriller/Miss Driller.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/multris/Multris.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/nebulus/Nebulus.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/neverball/Neverball.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/neverball/Neverputt.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/nonny/Nonny.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/npuzzle/NPuzzle.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/openblok/OpenBlok.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/openggs/Open Great Giana Sisters.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/opensupaplex/OpenSupaplex.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/raptor/Raptor.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/sdlsopwith/SDL Sopwith.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/waternet/Waternet.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/zeldaolb/zeldaolb.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.

2024-07-25 15:20 UTC, JeodC commented on ports/zgloom/ZGloom.sh
> -source $controlfolder/control.txt
Removes `source $controlfolder/control.txt`, so cannot use `get_controls`, cannot set `$directory`.