New Port: Sonic TT 16-Bit (& Mystik Belle Fix)
PortsMaster/PortMaster-New pull request #555
Opened 2024-07-24 19:05 UTC by JeodC

# New Port for Sonic Triple Trouble 16-Bit

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## Additional Resources
Mystik Belle fix included in this PR. Tested and now working in muOS. Was likely also broken elsewhere.

2024-07-26 21:19 UTC, JeodC commented
Ready for review :)

2024-07-27 02:17 UTC, Cebion requested changes

2024-07-27 02:17 UTC, Cebion commented on ports/sonictt16b/port.json
> +    "portname/"
Portname/

2024-07-27 02:17 UTC, Cebion commented on ports/sonictt16b/port.json
> +    "reqs": []
Architecture missing

2024-07-27 02:39 UTC, Cebion approved these changes

2024-07-27 05:33 UTC, kloptops requested changes
Just a small change in the `port.json`. 😄

2024-07-27 05:33 UTC, kloptops commented on ports/sonictt16b/port.json
> +    "reqs": ["aarch64"]
This should be in the `"arch"` tag.
```suggestion
    "reqs": [],
    "arch": ["aarch64"]
```

2024-07-27 08:03 UTC, kloptops commented on ports/sonictt16b/port.json
> +    "reqs": ["aarch64"]
The requirements attribute isn't for filtering architecture.

2024-07-27 11:42 UTC, kloptops approved these changes

2024-07-27 11:42 UTC, merged