BENBO QUEST
PortsMaster/PortMaster-New pull request #561
Opened 2024-07-27 13:06 UTC by JeodC

# New Port for BENBO QUEST

## Game Information
- **Title**: BENBO QUEST
- **URL**: [BENBO QUEST](https://thumbtack.itch.io/benboquest)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX (probably)
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

![image](https://github.com/user-attachments/assets/68d3c07f-89d5-4619-a8ff-39b96f241099)

2024-07-27 13:13 UTC, kloptops requested changes

2024-07-27 13:13 UTC, kloptops commented on ports/benboquest/port.json
> +        "reqs": ["armhf"]
Just this one again? 😁

2024-07-27 13:18 UTC, kloptops approved these changes

2024-07-28 14:38 UTC, tabreturn approved these changes

2024-07-28 15:45 UTC, merged