Add Undertale Yellow
PortsMaster/PortMaster-New pull request #568
Opened 2024-07-31 12:06 UTC by JeodC

# New Port for Undertale Yellow

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-08-01 12:05 UTC, kloptops requested changes

2024-08-01 12:05 UTC, kloptops commented on ports/utyellow/port.json
> +    "reqs": []
Missing comma:
```suggestion
    "reqs": [],
```

2024-08-01 12:17 UTC, JeodC commented
I might mark this one experimental later.

2024-08-03 12:04 UTC, Cebion commented on ports/utyellow/Undertale Yellow.sh
> +export LD_LIBRARY_PATH="$GAMEDIR/lib:$GAMEDIR/libs":$LD_LIBRARY_PATH
Isn't the ld_library export done above already?

2024-08-03 12:04 UTC, Cebion commented on ports/utyellow/port.json
Is this a old json format template you're using? The one from the website has fields for inst_md and  desc_md.

2024-08-03 12:18 UTC, JeodC commented on ports/utyellow/port.json
Yes I didn't know the website had a new json version.

2024-08-03 14:45 UTC, kloptops approved these changes

2024-08-06 10:49 UTC, kloptops approved these changes
👍

2024-08-06 14:32 UTC, Cebion approved these changes

2024-08-06 14:32 UTC, merged