Add port: Zelda II Enhanced
PortsMaster/PortMaster-New pull request #580
Opened 2024-08-05 19:45 UTC by JeodC

# New Port for Zelda II Enhanced

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-08-05 20:36 UTC, Cebion requested changes

2024-08-05 20:36 UTC, Cebion commented on ports/ziiaol/Zelda II Enhanced.sh
> +export PORT_32BIT="Y"
Export 32 bit two times present

2024-08-05 20:36 UTC, Cebion commented on ports/ziiaol/port.json
> +    "inst_md": "Download the .zip from https://hoverbat.itch.io/ziiaol and put in the gamedata folder.",
If that markdown section is the same as the normal one we just use one field. It's just to make the details page prettier with the md links. Or if the instructions are big we can just put small text one in the normal field and go crazy on the md field

2024-08-05 20:36 UTC, Cebion commented on ports/ziiaol/port.json
> +      "aarch64"
gmloader arch is armhf

2024-08-06 01:35 UTC, Cebion approved these changes

2024-08-06 01:56 UTC, kloptops approved these changes

2024-08-06 01:57 UTC, merged