Add New Port Jester's Helper
PortsMaster/PortMaster-New pull request #581
Opened 2024-08-05 21:44 UTC by MadShmupper

# New Port for { Jester's Helper }

## Game Information
- **Title**: { Jester's Helper }
- **URL**: { https://all-x.itch.io/jesters-helper }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-06 10:51 UTC, kloptops approved these changes

2024-08-06 12:20 UTC, Cebion requested changes

2024-08-06 12:20 UTC, Cebion commented on ports/jestershelper/Jester's Helper.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
Wrong ld_library_path export.

2024-08-06 12:20 UTC, Cebion commented on ports/jestershelper/cover.png
This is just a screenshot. If you don't have a cover just use the screenshot as cover and inside the game info.xml

2024-08-07 11:53 UTC, JeodC approved these changes

2024-08-07 13:14 UTC, Cebion approved these changes

2024-08-07 13:14 UTC, merged