New Port Operius
PortsMaster/PortMaster-New pull request #586
Opened 2024-08-09 03:07 UTC by Fraxinus88

# New Port for Operius

## Game Information
- **Title**: Operius
- **URL**: https://gamejolt.com/games/operius/638794

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-09 12:26 UTC, kloptops requested changes
Just the possible small script issue, otherwise looks good.

2024-08-09 15:05 UTC, Fraxinus88 commented on ports/operius/Operius.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$GAMEDIR/utils/libs"
alrighty :)

2024-08-10 12:06 UTC, kloptops approved these changes

2024-08-10 12:57 UTC, Cebion approved these changes

2024-08-10 12:57 UTC, merged