Remove usage of arrays from VCMI.sh
PortsMaster/PortMaster-New pull request #596
Opened 2024-08-16 22:13 UTC by ahobsonsayers

Using arrays causes issues when running on Trimui Smart Pro. I am not sure why this is, but I was able to identify the issue from the logs. This PR simply removes usage of bash arrays, and replaces them with alternative, but equivalent logic

2024-08-17 06:27 UTC, MichalZaniewicz approved these changes

2024-08-18 06:09 UTC, kloptops requested changes

2024-08-18 06:09 UTC, kloptops commented on ports/vcmi/VCMI.sh
You'll need to do something like this:
```sh
    # Install from gog installer
    EXE_FILE=setup_heroes_of_might_and_magic_3_*.exe
    BIN_FILE=setup_heroes_of_might_and_magic_3_*.bin
    FILES_TO_REMOVE="$EXE_FILE $BIN_FILE"
    BUILDER_OPTIONS="--gog $EXE_FILE"
```

2024-08-19 18:23 UTC, ahobsonsayers commented on ports/vcmi/VCMI.sh
You are right that wildcards don't work in double quotes in bash, but this doesn't seem to be an issue here as the string is being passed to the the `vcmibuilder` which seems to handle the wildcards correctly. I tested this with my GOG version of the game (which includes a build number after the 3) and this worked fine, implying thosnis not a problem.

Regardless, I'm happy to change it if it is preferred! Thanks for looking

2024-09-04 17:23 UTC, Cebion commented
Closed due to inactivity

2024-09-04 17:23 UTC, closed without merging

2024-12-24 21:20 UTC, ahobsonsayers commented
@Cebion can I get this re-opened? Apologies for being inactive leading to this being closed - my life got busy, and I was happy I just use my custom script.

I am going to make the suggested changed now, and would love to get this merged

2024-12-24 21:30 UTC, ahobsonsayers commented
Actually, don't worry, I have opened a new PR here #1091

I will endeavour to get this one merged!