New Port: Jump n Bump
PortsMaster/PortMaster-New pull request #60
Opened 2024-02-06 10:21 UTC by monkeyx-net

# New Port for Jump n Bump
## Game Information
- **Title**: Jump n Bump
- **URL**:  https://github.com/fabiangreffrath/jumpnbump

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x ] AmberELEC
- [x ] ArkOS
- [ x] JELOS

### Resolution Tests
Test all major resolutions:
- [ x] 480x320
- [x ] 640x480
- [x ] 720x720 (RGB30)
- [x ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-02-06 10:32 UTC, Cebion approved these changes
:+1:

2024-02-06 21:43 UTC, tabreturn requested changes

2024-02-06 21:43 UTC, tabreturn commented on ports/jumpnbump/README.md
L1 and L2 appear mapped to keys but aren't listed in the Controls here

2024-02-07 09:48 UTC, kloptops approved these changes
👍

2024-02-07 11:15 UTC, Cebion commented
F10 toggles fullscreen
ESC ends the game
F12 closes the game and quits

Has no relevance.

2024-02-07 11:16 UTC, merged