Add New Port L'Abbaye des Morts
PortsMaster/PortMaster-New pull request #601
Opened 2024-08-17 23:05 UTC by MadShmupper

# New Port for { L'Abbaye des Morts }

## Game Information
- **Title**: { L'Abbaye des Morts }
- **URL**: { https://github.com/nevat/abbayedesmorts-gpl }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-18 06:16 UTC, kloptops requested changes

2024-08-18 06:16 UTC, kloptops commented on ports/abbayedesmorts/cover.png
Cover should not just be a different screenshot of the game.

2024-08-18 06:30 UTC, MadShmupper commented on ports/abbayedesmorts/cover.png
Okay. Thanks, I just changed it to using same image as my screenshot

2024-08-19 08:01 UTC, Cebion requested changes

2024-08-19 08:01 UTC, Cebion commented on ports/abbayedesmorts/screenshot.png
Did you take this screenshot?
Because it looks like a filter was thrown on top of it to make it smooth.

Reference:

https://raw.githubusercontent.com/nevat/abbayedesmorts-gpl/master/screenshots/ingame-md.png

2024-08-20 00:43 UTC, MadShmupper commented on ports/abbayedesmorts/abbayedesmorts/libs/libSDL2_mixer-2.0.so.0
This uses sdl2. Don't know how those others got in but got now.

2024-08-20 01:01 UTC, MadShmupper commented on ports/abbayedesmorts/abbayedesmorts/libs/moarlibs.7z
These were  a collection of all libs the game uses, if a cfw was missing a lib, could pull it from here. Left in for testing purposes and forgot to take them out before uploading.

2024-08-20 03:23 UTC, MadShmupper commented on ports/abbayedesmorts/README.md
No. This is compiled by Slayer366. The READ.ME has now been updated to show compiling and the modified source code is included.

2024-08-20 03:35 UTC, Slayer366 approved these changes

2024-08-20 04:01 UTC, MadShmupper commented on ports/abbayedesmorts/screenshot.png
It's been replaced.

2024-08-20 04:01 UTC, MadShmupper commented on ports/abbayedesmorts/cover.png
👍

2024-08-20 04:09 UTC, Slayer366 approved these changes

2024-08-20 07:18 UTC, Cebion approved these changes

2024-08-20 07:19 UTC, merged

2024-08-20 10:21 UTC, MadShmupper commented on ports/abbayedesmorts/cover.png
Fixed that btw