add supergaelicdodgeball
PortsMaster/PortMaster-New pull request #603
Opened 2024-08-18 19:42 UTC by zehmaluco

New Port for { Super Gaelic Dodgeball }
Game Information
Title: { Super Gaelic Dodgeball }
URL: { https://shoehead.itch.io/sgdb }
Submission Requirements
CFW Tests
Ensure your game has been tested on all major CFWs:

[ x] AmberELEC
[ x] ArkOS
[ x] ROCKNIX
[ x] muOS
Resolution Tests
Test all major resolutions:

[x ] 480x320
[x ] 640x480
[x ] 720x720 (RGB30)
[x ] Higher resolutions (e.g., 1280x720)
File Structure
Your port should have the following structure:
portname/
port.json
README.md
screenshot.jpg
cover.jpg
gameinfo.xml
Port Name.sh
portname/
Additional Resources
For an in-depth guide on creating a pull request, refer to: PortMaster Game Packaging Guide

# New Port for { Game Title }

## Game Information
- **Title**: { Game Title }
- **URL**: { Link to project page or source control page }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [ ] ArkOS
- [ ] ROCKNIX
- [ ] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [ ] 640x480
- [ ] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-18 20:14 UTC, JeodC commented
`port.json`, `readme.md`, and `cover.png`, `screenshot.png` all need to be in the same folder as the `.sh` file. Not inside the portfolder.

2024-08-18 20:20 UTC, zehmaluco commented
> `port.json`, `readme.md`, and `cover.png`, `screenshot.png` all need to be in the same folder as the `.sh` file. Not inside the portfolder.

Done. :)

2024-08-19 07:50 UTC, Cebion requested changes
README.MD is also missing.

Check the packaging guide on our website

https://portmaster.games/packaging.html

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/Super Gaelic Dodgeball.sh
> +if [ -f "${controlfolder}/libgl_${CFWNAME}.txt" ]; then
gmloader does not use libgl

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/cover.png
cover has to be 640x480

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/gameinfo.xml
> +    <publisher>Icth.io</publisher>
Typo, and is itch really the publisher or just the hoster?
Hoster is not publisher

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/port.json
> +        "rtr": true,
If this game is rtr it needs license files. Else it's not ready to run.

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/port.json
> +        "inst": "Get the game on Itch.io and place all files on the "gamedata" portfolder.",
Where exactly?

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/screenshot.png
Screenshot has to be 640x480

2024-08-19 07:50 UTC, Cebion commented on ports/supergaelicdodgeball/supergaelicdodgeball/log.txt
log.txt can be deleted

2024-08-19 10:12 UTC, zehmaluco commented
Made the changes. Thanks for the patience, dudes. I'm still getting used to Git. :)

2024-08-19 12:37 UTC, zehmaluco commented
Made the changes. 👍

2024-08-19 15:42 UTC, Cebion approved these changes

2024-08-20 15:36 UTC, zehmaluco commented
Sorry, Cebion. I've didn't know I could only do a pull at a time and add one more project file on this pull. My bad, sorry 😛

2024-08-20 15:50 UTC, Cebion commented
> Sorry, Cebion. I've didn't know I could only do a pull at a time and add one more project file on this pull. My bad, sorry 😛

Yeah you have to work with branches.

2024-08-20 18:28 UTC, Cebion submitted a review, later dismissed

2024-08-20 20:17 UTC, zehmaluco commented
@Cebion @JeodC i've updated the cover.png to look similar to Jeod template. Sorry for the back and forth on this. 🙇

2024-08-21 07:48 UTC, Cebion submitted a review, later dismissed

2024-08-21 10:58 UTC, kloptops requested changes
port.json is borked. 😄

2024-08-21 11:07 UTC, zehmaluco commented
> port.json is borked. 😄

Fixed. :)

2024-08-21 17:06 UTC, Cebion reviewed
But why :D

2024-08-21 17:06 UTC, Cebion submitted a review, later dismissed

2024-08-22 07:22 UTC, kloptops commented on ports/supergaelicdodgeball/port.json
> +        "inst_md": null,
Probably a good idea to add "inst_md" with an actual link to the game:
```suggestion
        "inst_md": "Get the game on the [shoehead itch.io page](https://shoehead.itch.io/sgdb), and place all game files in the ports/supergaelicdodgeball/gamedata/ directory.",
```

2024-08-22 09:52 UTC, zehmaluco commented
Fixed the inst_md on the port.json @Cebion @kloptops

2024-08-22 09:53 UTC, kloptops approved these changes

2024-08-22 10:31 UTC, kloptops requested changes

2024-08-22 10:31 UTC, kloptops commented on ports/supergaelicdodgeball/port.json
> +    "version": 1,
this should be version 3.
```suggestion
    "version": 3,
```

2024-08-22 10:44 UTC, kloptops approved these changes

2024-08-22 16:38 UTC, JeodC approved these changes

2024-08-22 16:38 UTC, merged