Megaman X8 16-bit
PortsMaster/PortMaster-New pull request #604
Opened 2024-08-19 11:21 UTC by Damian2809

# New Port for { Megaman X8 16-bit }

## Game Information
- **Title**: { MegaMan X8 16-bit }
- **URL**: { https://sonicfangameshq.com/forums/showcase/mega-man-x8-16-bit-demo3.1504/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X TESTED BUT NOT VERY GOOD] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-20 07:14 UTC, Cebion requested changes

2024-08-20 07:14 UTC, Cebion commented on ports/megamanx816-bit/README.md
> +https://sonicfangameshq.com/forums/showcase/mega-man-x8-16-bit-demo3.1504/ grab the zip from here, extract it and rename the File to "Megaman X8 FC.pck" after that put it in megamanx816-bit/gamedata
Notes section is for thank you notes with links to the developer etc. 
Instructions go into port.json

2024-08-20 07:14 UTC, Cebion commented on ports/megamanx816-bit/cover.png
If a cover is used has to show also gameplay not just the logo.
Else just use a screenshot.
If using a cover / screenshot has to be 640x480 in resolution.

2024-08-20 07:14 UTC, Cebion commented on ports/megamanx816-bit/port.json
> +  "name": "megamanx8.zip",
zip name and folder name have to match

2024-08-20 07:14 UTC, Cebion commented on ports/megamanx816-bit/screenshot.png
screenshot has to be 640x480, and no collage

2024-08-20 16:36 UTC, Damian2809 commented on ports/megamanx816-bit/port.json
> +  "name": "megamanx8.zip",
that should be fixed now

2024-08-21 07:24 UTC, Cebion requested changes

2024-08-21 07:24 UTC, Cebion commented on ports/megamanx816-bit/README.md
Readme is missing credits, see other README.md for reference.

2024-08-21 12:16 UTC, Damian2809 commented on ports/megamanx816-bit/README.md
done hope thats good

2024-08-22 02:51 UTC, Slayer366 approved these changes

2024-08-22 07:03 UTC, Cebion requested changes

2024-08-22 07:03 UTC, Cebion commented on ports/megamanx816-bit/port.json
> +    "inst": "https://sonicfangameshq.com/forums/showcase/mega-man-x8-16-bit-demo3.1504/ grab the zip from here, extract it and rename the File to "Megaman X8 FC.pck" after that put it in megamanx816-
Invalid JSON!
Error: Parse error on line 16:
...rename the File to "Megaman X8 FC.pck" a
-----------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'undefined'

You have 3x " in there

2024-08-22 19:00 UTC, Cebion requested changes

2024-08-22 19:00 UTC, Cebion commented on ports/megamanx816-bit/port.json
> +    "desc": "he Mega Man X8 16-Bit Demake is a fan-made project that reimagines the original Mega Man X8 in the style of the classic 16-bit era. This demake brings the modern aesthetics and mechanics
Introduced a typo

2024-08-23 08:46 UTC, Cebion approved these changes

2024-08-23 09:07 UTC, kloptops approved these changes

2024-08-23 09:07 UTC, merged