Add new Port: NetSurf Web Browser
PortsMaster/PortMaster-New pull request #606
Opened 2024-08-20 17:55 UTC by Cebion

NetSurf

Game Information

Title: NetSurf
URL: [https://www.asahi-net.or.jp/~cs8k-cyu/windows/a7xpg_e.html](https://github.com/tailtwo/netsurf)

Onscreen keyboard can be accessed on the bottom right corner (A) symbol.

CFW Tests
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] muOS

[X] TSP Crossmix (Optional)
[]  Knulli (Optional) 

Resolution Tests
Test all major resolutions:
[] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

2024-08-21 11:29 UTC, kloptops requested changes

2024-08-21 11:29 UTC, kloptops commented on ports/netsurf/README.md
> +Thanks to the [Netsurf Team] (https://www.netsurf-browser.org/) for creating this browser.
Syntax error in markdown:
```suggestion
Thanks to the [Netsurf Team](https://www.netsurf-browser.org/) for creating this browser.
```

2024-08-21 13:44 UTC, cdeletre requested changes
Just one markdown syntax error in README.md :)

2024-08-21 13:44 UTC, cdeletre commented on ports/netsurf/README.md
> +| HK + X| Refresh (F5)
markdown syntax error, missing a `|` a the end

2024-08-21 21:29 UTC, merged

2024-10-20 18:02 UTC, helio-marcos commented
hello friend! Thank you for your contributions to PortMaster!
I added an option to Netsurf.sh to work on Arkos-Aeolux, the CFW_NAME" = " AeUX"
![netsurf](https://github.com/user-attachments/assets/aa6e492d-1b06-4bea-810d-0346d3fb75d2)