New Port Kaima
PortsMaster/PortMaster-New pull request #607
Opened 2024-08-20 19:47 UTC by Tlaggypyro

# New Port for { Kaima}

## Game Information
- **Title**: {Kaima}
- **URL**: { https://nomnomnami.itch.io/kaima }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-20 21:00 UTC, cdeletre commented on ports/kaima/kaima.sh
The name of the `.sh` script should start with uppercase letter.

2024-08-21 11:43 UTC, kloptops requested changes
Lots of files are NULL padded. Not sure what has happened here. 🐢 🤔

<img width="715" alt="Screenshot 2024-08-21 at 7 42 54 PM" src="https://github.com/user-attachments/assets/c6bcbadb-b604-4575-a4b9-d33bf814838f">

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/Kaima.sh
Not sure what has happened here, but the file is NULL padded at the end?

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/README.md
And this file is null padded.

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/gameinfo.xml
And this file...

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/kaima/conf/mkxp.conf
And this file....

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/kaima/kaima.gptk
And again.

2024-08-21 11:43 UTC, kloptops commented on ports/kaima/port.json
this too.

2024-08-21 12:21 UTC, Tlaggypyro commented on ports/kaima/Kaima.sh
How do I fix that?

2024-08-21 13:20 UTC, cdeletre commented on ports/kaima/Kaima.sh
With Linux you can run this command
`tr < README.md -d '\000' > README-clean.md`

2024-08-21 13:27 UTC, cdeletre commented on ports/kaima/Kaima.sh
With Windows you can use this trick https://stackoverflow.com/questions/19332949/removing-nul-characters which works in Notepad++. It should work in other text editors such as Visual Studio Code (just check how to use regular expression)

2024-08-22 08:13 UTC, kloptops commented on ports/kaima/Kaima.sh
> How do I fix that?

I am not sure how you even managed it?

Was it a bug in uploading to github?

2024-08-22 20:10 UTC, Tlaggypyro commented
I reuploaded everything did that fix it by chance

2024-08-22 22:26 UTC, JeodC commented on ports/kaima/LICENSE_falcon-mkxp
This file needs to go in the portfolder.

2024-08-23 08:45 UTC, Cebion requested changes

2024-08-23 08:45 UTC, Cebion commented on ports/kaima/Kaima.sh
Nope, still broken

![image](https://github.com/user-attachments/assets/ba1b6f75-daf5-48eb-90c8-536ab1e42637)

2024-08-23 08:45 UTC, Cebion commented on ports/kaima/Kaima.sh
File is in ANSI and has NUL.
Not sure how you edited / saved these files.
Best to copy your changes into new files.
On a PC.

2024-08-30 22:15 UTC, closed without merging