Add New Port Mire
PortsMaster/PortMaster-New pull request #608
Opened 2024-08-20 22:38 UTC by MadShmupper

Add New Port Mire

# New Port for { Mire }

## Game Information
- **Title**: { Mire }
- **URL**: { https://bagelcollie.itch.io/mire }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-21 07:12 UTC, Cebion requested changes

2024-08-21 07:12 UTC, Cebion commented on ports/mire/Mire.sh
> +# PORTMASTER: mire.zip, Mire.sh
This is autogenerated by PortMaster. Not needed

2024-08-21 07:12 UTC, Cebion commented on ports/mire/Mire.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
wrong LD_LIBRARY_PATH, you fixed it in your other releases =)

2024-08-21 07:12 UTC, Cebion commented on ports/mire/cover.png
Cover should not be just a screenshot!
If you only have a screenshot don't use a cover.
Instead use screenshot.png in your gameinfo.xml

2024-08-21 07:12 UTC, Cebion commented on ports/mire/port.json
> +    "status": {
You added a port.json from an installed copy. None of the bottom fields should be in it =)

2024-08-21 13:04 UTC, Cebion approved these changes

2024-08-22 02:46 UTC, Slayer366 approved these changes

2024-08-22 07:01 UTC, merged