Gumchu girl
PortsMaster/PortMaster-New pull request #618
Opened 2024-08-28 23:42 UTC by MadShmupper

# New Port for { GUMCHU GIRL }

## Game Information
- **Title**: { GUMCHU GIRL }
- **URL**: { https://caseportman.itch.io/gumchu-girl-demo }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-29 09:12 UTC, kloptops requested changes

2024-08-29 09:12 UTC, kloptops commented on ports/simonsqrev/README.md
Why is this port being affected here? 🐢

2024-08-29 10:04 UTC, MadShmupper commented on ports/simonsqrev/README.md
Yikes. I'm sorry. I'm uncertain what I may have done. I'll look closer when I wake.  Sorry

2024-08-30 07:13 UTC, Cebion commented on ports/simonsqrev/README.md
This happens if you don't switch to main before making a new branch for example =)

2024-08-30 13:34 UTC, closed without merging

2024-08-30 13:35 UTC, MadShmupper commented
Closing to fix it. Will reopen soon