New port Kaima
PortsMaster/PortMaster-New pull request #620
Opened 2024-08-30 22:51 UTC by Tlaggypyro

# New Port for {Kaima }

## Game Information
- **Title**: { Kaima}
- **URL**: { https://nomnomnami.itch.io/kaima }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-08-31 20:24 UTC, Cebion requested changes

2024-08-31 20:24 UTC, Cebion commented on ports/Kaima/port.json
> +        "redtrees"
foldername and zipname do not match.

2024-09-02 11:25 UTC, Cebion approved these changes

2024-09-03 06:35 UTC, Cebion requested changes
Foldernames are uppercase for both folders

2024-09-03 14:30 UTC, Tlaggypyro commented
fixed

2024-09-03 14:32 UTC, Cebion requested changes

2024-09-03 14:32 UTC, Cebion commented on ports/kaima/port.json
> +    "name": "Kaima.zip",
zip name needs to be lowercase

2024-09-03 14:32 UTC, Cebion commented on ports/kaima/port.json
> +        "Kaima"
foldername needs to be lowercase

2024-09-03 15:51 UTC, Cebion approved these changes

2024-09-04 15:40 UTC, JeodC approved these changes

2024-09-04 15:40 UTC, merged