New Port Hyper Princess Pitch
PortsMaster/PortMaster-New pull request #625
Opened 2024-09-01 12:58 UTC by Fraxinus88

# New Port for Hyper Princess Pitch

## Game Information
- **Title**: Hyper Princess Pitch
- **URL**: https://remar.se/daniel/pitch.php

## Submission Requirements

### CFW Tests
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS

Architectures: 
[X] armHF
[X] Panfrost (Mainline)

Resolutions: 
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-01 13:00 UTC, Cebion requested changes

2024-09-01 13:34 UTC, Fraxinus88 commented on ports/hyperprincesspitch/Hyper Princess Pitch.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$GAMEDIR/utils/libs:$LD_LIBRARY_PATH"
Okies updated!

2024-09-01 13:35 UTC, Fraxinus88 commented
Also modified the game.droid text of CROSS --> A and SQUARE to X

2024-09-02 11:20 UTC, Cebion approved these changes

2024-09-03 05:29 UTC, Slayer366 approved these changes

2024-09-03 06:34 UTC, merged