New port: Globeba
PortsMaster/PortMaster-New pull request #637
Opened 2024-09-05 18:32 UTC by JanTrueno

# New Port for Globeba

## Game Information
- **Title**: Globeba
- **URL**: https://team-bugulon.itch.io/globeba

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-07 17:09 UTC, Cebion requested changes

2024-09-07 17:09 UTC, Cebion commented on ports/globeba/globeba/log.txt
log can be deleted

2024-09-08 00:37 UTC, tabreturn approved these changes

2024-09-08 03:39 UTC, kloptops approved these changes

2024-09-08 12:04 UTC, Cebion approved these changes

2024-09-08 12:04 UTC, merged