Unlikely
PortsMaster/PortMaster-New pull request #650
Opened 2024-09-11 17:51 UTC by Damian2809

# New Port for Unlikely

## Game Information
- **Title**: Unlikely
- **URL**: https://nachogames.itch.io/unlikely

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-11 18:00 UTC, JanTrueno requested changes

2024-09-11 18:00 UTC, JanTrueno commented on ports/unlikely/cover.png
Can you get a higher quality version of this cover? And please compress it as well.

2024-09-11 18:00 UTC, JanTrueno commented on ports/unlikely/README.md
Everything else?

2024-09-11 18:00 UTC, JanTrueno commented on ports/unlikely/screenshot.png
Compress the screenshot as well please.

2024-09-11 18:09 UTC, Damian2809 commented on ports/unlikely/README.md
what are you missing? i just used the basic readme.md

2024-09-11 18:13 UTC, JanTrueno commented on ports/unlikely/screenshot.png
I sent some revised images on discord :)

2024-09-12 06:06 UTC, JanTrueno commented on ports/unlikely/README.md
"|Everything else|Left Mouse |"
This is what I mean ^^ Just tell the users what controls the left mouse click.

2024-09-14 19:44 UTC, Cebion approved these changes

2024-09-14 22:21 UTC, JanTrueno approved these changes

2024-09-14 22:22 UTC, merged