Add new port Fallen Leaf
PortsMaster/PortMaster-New pull request #653
Opened 2024-09-13 02:27 UTC by cdeletre

# New Port for Fallen Leaf

## Game Information
- **Title**: Fallen Leaf
- **URL**: [Fallen Leaf](https://eldenpixels.com/indie-highlight-fallen-leaf/)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

GPU driver:
- [x] Panfrost
- [x] Mali

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure

```
.
├── compress.txt
├── game.apk
├── gamedata
│   └── put_your_files_here.txt
├── gmloader
├── libc++_shared.so
├── libs
│   ├── libcrypto.so.1.1
│   └── libzip.so.5
├── splash-1.png
├── splash-2.png
├── splash-3.png
├── splash-install.png
├── swapabxy.txt
└── tools
    ├── gmKtool.py
    ├── libs
    │   ├── libFLAC.so.8
    │   ├── libogg.so.0
    │   ├── libvorbis.so.0
    │   └── libvorbisenc.so.2
    ├── oggenc
    ├── splash
    └── swapabxy.py
````

2024-09-13 06:16 UTC, JanTrueno requested changes

2024-09-13 06:16 UTC, JanTrueno commented on ports/fallenleaf/Fallen Leaf.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$TOOLDIR/libs:$LD_LIBRARY_PATH"
Cebion wont like this libpath ^^

2024-09-13 06:16 UTC, JanTrueno commented on ports/fallenleaf/port.json
> +    "inst": "Copy data.win and audiogroup1.dat into the gamedata folder",
Link to the store would be nice here, or in the readme :)

2024-09-14 19:42 UTC, Cebion approved these changes

2024-09-14 22:22 UTC, JanTrueno approved these changes

2024-09-14 22:22 UTC, merged