New Port ElecHead
PortsMaster/PortMaster-New pull request #660
Opened 2024-09-15 06:20 UTC by Fraxinus88

# New Port for ElecHead

## Game Information
- **Title**: ElecHead
- **URL**: https://namatakahashi.itch.io/elechead

## Submission Requirements

### CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS

Architectures: 
[X] aarch64
[X] Panfrost (Mainline)

Resolutions: 
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-15 11:11 UTC, kloptops requested changes

2024-09-15 11:11 UTC, kloptops commented on ports/elechead/port.json
> +    "desc": "⚡＋🤖＋🧩",
Not sure this will work. 😁

2024-09-15 11:11 UTC, kloptops commented on ports/elechead/cover.png
This is the same as the screenshot?

2024-09-15 12:10 UTC, Fraxinus88 commented on ports/elechead/cover.png
Whoops

2024-09-15 12:10 UTC, Fraxinus88 commented on ports/elechead/port.json
> +    "desc": "⚡＋🤖＋🧩",
Can we try :p

2024-09-15 12:19 UTC, kloptops commented on ports/elechead/port.json
> +    "desc": "⚡＋🤖＋🧩",
Sure. :)

2024-09-15 12:21 UTC, kloptops approved these changes
Good luck. Let me know when you want to update the port.json file with real info. 😄

2024-09-16 08:03 UTC, Cebion approved these changes

2024-09-16 08:03 UTC, merged