New Port: Biolab Disaster
PortsMaster/PortMaster-New pull request #666
Opened 2024-09-16 18:43 UTC by scemino

# New Port for Biolab Disaster

## Game Information
- **Title**: Biolab Disaster
- **URL**: https://github.com/scemino/z_biolab

## Notes

Thanks to [Dominic Szablewski](https://github.com/phoboslab/) for creating this awesome game and game engine.

## Controls

| Button | Action |
|--|--| 
|DPAD|Move|
|A|Shoot|
|B|Jump|

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

2024-09-16 20:14 UTC, cdeletre commented on ports/biolab/Biolab Disaster.sh
> +export DEVICE_ARCH="${DEVICE_ARCH:-aarch64}"
Not sure we still need this line.

2024-09-16 20:29 UTC, cdeletre commented
Only 640x480 has been validated ?

2024-09-16 20:34 UTC, scemino commented
> Only 640x480 has been validated ?
> 
> Looking at the testing thread I suppose more resolutions are ok. But you know more than me :)

Sorry I validated 480x320 with my RG351M.

2024-09-16 22:23 UTC, cdeletre commented
> ✅ 353VS / OGA Arkos, Ace Rocknix and 35xxSP muOS. The game seems to run fullscreen no matter what, so its a bit stretched on 4:3 and I bet it will look hillarious on 1:1 screens, but plays fine nonetheless

I think you can add high resolution (Ace test) 🙃

2024-09-17 05:00 UTC, scemino commented on ports/biolab/port.json
> +    "exp": true,
When do you check this? I don't know ☺️

2024-09-17 05:01 UTC, scemino commented on ports/biolab/Biolab Disaster.sh
> +export DEVICE_ARCH="${DEVICE_ARCH:-aarch64}"
Which line 26 or 28?

2024-09-17 08:23 UTC, Cebion requested changes

2024-09-17 08:23 UTC, Cebion commented on ports/biolab/Biolab Disaster.sh
> +export DEVICE_ARCH="${DEVICE_ARCH:-aarch64}"
This one is not needed anymore. Was for transitioning in multiarch ports.

2024-09-17 08:23 UTC, Cebion commented on ports/biolab/biolab/.DS_Store
mac files have to be cleaned

2024-09-17 08:23 UTC, Cebion commented on ports/biolab/port.json
> +    "exp": true,
This line, if its experimental ti won'T show up in Portmaster unless you know what you're doing.

2024-09-17 09:38 UTC, scemino commented on ports/biolab/biolab/.DS_Store
> mac files have to be cleaned

Sorry about that, I'm not familiar with WEB UI. I'm still figuring out how to remove these files from the WEB.

2024-09-17 09:47 UTC, scemino commented on ports/biolab/biolab/.DS_Store
That was painful but it's done.

2024-09-17 10:11 UTC, JanTrueno requested changes
Portfiles are not in the correct structure, please reference this:
- portname/
  - port.json
  - README.md
  - screenshot.jpg
  - gameinfo.xml
  - cover.jpg (Optional)
  - Port Name.sh
  - portname/
    - <portfiles here>
    - LICENSE Files

2024-09-17 10:11 UTC, JanTrueno commented on ports/biolab/cover.png
Cover is wrong resolution. Needs to be 640x480.

2024-09-17 10:11 UTC, JanTrueno commented on ports/biolab/screenshot.png
Also needs to be 640x480 in resolution :)

2024-09-17 10:18 UTC, scemino commented on ports/biolab/screenshot.png
sorry I misunderstood this: https://portmaster.games/packaging.html#screenshot

> The screenshot has to be at least 640x480 in dimensions

2024-09-17 10:21 UTC, scemino commented
> Portfiles are not in the correct structure, please reference this:
> 
>     * portname/
>       
>       * port.json
>       * README.md
>       * screenshot.jpg
>       * gameinfo.xml
>       * cover.jpg (Optional)
>       * Port Name.sh
>       * portname/
>         
>         * 
>         * LICENSE Files

What file is not in the correct place? I don't see my error.

2024-09-17 11:13 UTC, JanTrueno commented
Seems like the instructions on the website arent correct. Your screenshot and cover look good now. About the structure, you have the cover/screenshot/xml/json all in the portfolder. They should be one folder higher, next to the README and script.

2024-09-17 11:18 UTC, scemino commented
> Seems like the instructions on the website arent correct. Your screenshot and cover look good now. About the structure, you have the cover/screenshot/xml/json all in the portfolder. They should be one folder higher, next to the README and script.

This seems all good no? They are next to the README file.
![Screenshot 2024-09-17 at 13 16 18](https://github.com/user-attachments/assets/4d910acb-6cea-4e1c-ab9e-49599a5db9b1)

2024-09-17 11:25 UTC, JanTrueno commented
Interesting, i have a different view on my end. 
![Knipsel](https://github.com/user-attachments/assets/9cb2e3bb-2c6c-41fd-af71-b4c626e02e8b)

2024-09-17 11:29 UTC, scemino commented
> Interesting, i have a different view on my end. ![Knipsel](https://private-user-images.githubusercontent.com/159560609/368143510-9cb2e3bb-2c6c-41fd-af71-b4c626e02e8b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzI3OTksIm5iZiI6MTcyNjU3MjQ5OSwicGF0aCI6Ii8xNTk1NjA2MDkvMzY4MTQzNTEwLTljYjJlM2JiLTJjNmMtNDFmZC1hZjcxLWI0YzYyNmUwMmU4Yi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTI4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2I4MDY1MmM0NGVmMTg1ZjM1ODk1YzY2Nzg1OTlmMGYyNTE3ZWZlMWJjYjBmYzMyZmIwNTNiNzVmYmEyZjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1nvw8pVSTI78FNRsa6SQVX4g7vU9bR2TP3U2dZUYuIE)

This is the same thing, the biolab folder is not expanded, so the files are not in the biolab subfolder.

2024-09-17 11:37 UTC, JanTrueno approved these changes
I was having a brainfart. Looks good ^^

2024-09-17 16:50 UTC, merged