Add New Port Operation S.T.E.E.L
PortsMaster/PortMaster-New pull request #682
Opened 2024-09-22 22:01 UTC by MadShmupper

Add New Port Operation S.T.E.E.L

# New Port for { Operation S.T.E.E.L }

## Game Information
- **Title**: { Operation S.T.E.E.L }
- **URL**: { https://leanderish.itch.io/steel }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-23 00:54 UTC, tabreturn reviewed
Neat port! I've left a few comments regarding metadata/info stuff.

2024-09-23 00:54 UTC, tabreturn commented on ports/operationsteel/port.json
The .sh path refers to a file named "OperationSTEEL.pck", but the instructions refer to "OperationSteel.pck"

2024-09-23 00:54 UTC, tabreturn commented on ports/operationsteel/screenshot.png
It looks like a JPG converted to a PNG (the JPG artefacts are visible). It's not a huge issue, but it would be nice if there were a better-quality graphic.

2024-09-23 00:54 UTC, tabreturn commented on ports/operationsteel/gameinfo.xml
Steam indicates the publisher is Undermog Games https://store.steampowered.com/app/1489300/Operation_STEEL

2024-09-23 02:56 UTC, MadShmupper commented on ports/operationsteel/gameinfo.xml
I think I've fixed it all. Thank you🙂🎩

2024-09-23 03:38 UTC, tabreturn approved these changes

2024-09-23 07:10 UTC, kloptops requested changes
Yeah a bit of work required. 😁

2024-09-23 07:10 UTC, kloptops commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +
Missing sourcing `device_info.txt` and `mod_cfw.txt`

2024-09-23 07:10 UTC, kloptops commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +# Ensure the conf directory exists
No logging statement.

2024-09-23 07:10 UTC, kloptops commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +"$runtime" --main-pack "gamedata/OperationSTEEL.pck"
This needs to be on one line, and have the `$GODOT_OPTS` variable.
`SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig" "$runtime" $GODOT_OPTS --main-pack`

2024-09-23 07:10 UTC, kloptops commented on ports/operationsteel/port.json
> +    "inst": "Purchase at itch.io https://leanderish.itch.io/steel "OR" Steam https://store.steampowered.com/app/1489300/Operation_STEEL/ -Locate OperationSTEEL.pck and place it into gamedata folder."
Syntax error, double quotes need to be escaped:
```suggestion
    "inst": "Purchase at itch.io https://leanderish.itch.io/steel \"OR\" Steam https://store.steampowered.com/app/1489300/Operation_STEEL/ -Locate OperationSTEEL.pck and place it into gamedata folder.",
```

2024-09-23 07:10 UTC, kloptops commented on ports/operationsteel/port.json
> +    "inst_md": "Purchase at [itch.io](https://leanderish.itch.io/steel) "OR" [Steam](https://store.steampowered.com/app/1489300/Operation_STEEL/) -Locate OperationSTEEL.pck and place it in to gamedat
```suggestion
    "inst_md": "Purchase at [itch.io](https://leanderish.itch.io/steel) \"OR\" [Steam](https://store.steampowered.com/app/1489300/Operation_STEEL/) -Locate OperationSTEEL.pck and place it in to gamedata folder.",
```

2024-09-23 07:11 UTC, Cebion approved these changes

2024-09-25 06:45 UTC, Cebion requested changes

2024-09-25 06:45 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +if [ -f "$controlfolder/device_info.txt" ]; then
Where did you get these IF statements from?

We're always setting these no matter what.
Only makes the .sh longer

2024-09-25 06:54 UTC, Cebion requested changes

2024-09-25 06:54 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +exec > >(tee -a "$GAMEDIR/log.txt") 2>&1
Wrong logging statement, I suggest you study our packaging guide with the example scripts again. 
We have a section where each function is explained.

2024-09-25 06:54 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig" "$runtime" $GODOT_OPTS --main-pack "gamedata/OperationSTEEL.pck"
SDL_gamecontrollerconfig is exported in a seperate line

2024-09-25 14:09 UTC, kloptops requested changes

2024-09-25 14:09 UTC, kloptops commented on ports/operationsteel/Operation S.T.E.E.L.sh
Huh?!

it’s now an empty file.

2024-09-25 14:12 UTC, MadShmupper commented on ports/operationsteel/Operation S.T.E.E.L.sh
Hmm..ok. I'm not sure what happened. I'll fix

2024-09-25 16:43 UTC, Cebion requested changes

2024-09-25 16:43 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +"$runtime" --main-pack "gamedata/OperationSTEEL.pck"
$GODOT_OPTS missing.
Check with the example godot script on our website.

2024-09-26 19:23 UTC, Cebion requested changes
Almost done =)

2024-09-26 19:23 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +#$ESUDO rm -rf ~/.operationsteel
`#` means its commented out so not active.
This meant if the game does use it uncomment else don#t use it.

2024-09-26 20:07 UTC, Cebion approved these changes

2024-09-27 10:58 UTC, kloptops requested changes

2024-09-27 10:58 UTC, kloptops commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +"$runtime" $GODOT_OPTS --main-pack "OperationSTEEL.pck"
missing `SDL_GAMECONTROLLERCONFIG`:
```suggestion
SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig" "$runtime" $GODOT_OPTS --main-pack "OperationSTEEL.pck"
```

2024-09-27 11:01 UTC, Cebion commented on ports/operationsteel/Operation S.T.E.E.L.sh
> +"$runtime" $GODOT_OPTS --main-pack "OperationSTEEL.pck"
This is set in line 32 via ```export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"```

2024-09-27 11:11 UTC, kloptops approved these changes

2024-09-27 11:11 UTC, merged