Add New Port Plague
PortsMaster/PortMaster-New pull request #684
Opened 2024-09-23 16:39 UTC by MadShmupper

Add New Port Plague

# New Port for { Plague }

## Game Information
- **Title**: { Plague }
- **URL**: { https://foletto.itch.io/plague }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-23 19:40 UTC, Cebion approved these changes

2024-09-23 22:55 UTC, MadShmupper commented
I've just gotten permission to r2r this one so I'll add what's needed this evening

2024-09-24 05:23 UTC, JanTrueno requested changes

2024-09-24 05:23 UTC, JanTrueno commented on ports/plague/cover.png
Needs to be 640x480.

2024-09-24 05:23 UTC, JanTrueno commented on ports/plague/screenshot.png
Also needs to be 640x480.

2024-09-24 12:14 UTC, JanTrueno requested changes

2024-09-24 12:14 UTC, JanTrueno commented on ports/plague/plague/gamedata/permission.png
Rename this to LICENSE.plague.png to keep some consistency with other licenses. Apart from that seems good :)

2024-09-24 12:25 UTC, MadShmupper commented on ports/plague/plague/gamedata/permission.png
Will do. Ty🎮

2024-09-24 12:52 UTC, JanTrueno approved these changes

2024-09-25 06:43 UTC, Cebion approved these changes

2024-09-25 06:43 UTC, merged