New port: Frogfall
PortsMaster/PortMaster-New pull request #690
Opened 2024-09-26 14:47 UTC by Ganimoth

# New Port for Frogfall

A free platformer made by Kultisti featuring an angry frog!
Special thanks to Kultisti (https://kultisti.itch.io/) for creating the game and allowing us to distribute the files! https://kultisti.itch.io/frogfall

 Controls:

| Button | Action |

| D-pad/Stick | Movement |
| A/B/X/Y | Jump |
| Select/Start | Pause | 

CFW Tests
[x] AmberELEC
[x] ArkOS
[x] JELOS / ROCKNIX
[x] muOS 

Architecture
[X] aarch64
[] Panfrost (Mainline) 

Resolution Tests
Test all major resolutions:
[x] 480x320 (Optional)
[x] 640x480
[x] 720x720 (RGB30)
[x] Higher resolutions (e.g., 1280x720

2024-09-26 17:32 UTC, Cebion requested changes

2024-09-26 17:32 UTC, Cebion commented on ports/frogfall/port.json
> +    "desc": "„it's fall in froggo town\ntime for a one final round\nto catch some flies!“\n\nA free platformer made by Kultisti featuring an angry frog! ",
Markdown in desc_md, and normal test in desc.

2024-09-26 18:17 UTC, Cebion approved these changes

2024-09-27 13:06 UTC, JanTrueno approved these changes
Looks good :)

2024-09-27 13:06 UTC, merged