Cognizance
PortsMaster/PortMaster-New pull request #696
Opened 2024-09-28 02:07 UTC by tabreturn

# New Port for { Game Title }

## Game Information
- **Title**: Cognizance
- **URL**: https://managore.itch.io/cognizance
- 
## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-09-28 07:56 UTC, Cebion requested changes

2024-09-28 07:56 UTC, Cebion commented on ports/cognizance/Cognizance.sh
> +export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs"
```suggestion
export LD_LIBRARY_PATH="/usr/lib32:$GAMEDIR/libs:$LD_LIBRARY_PATH"
```

2024-09-28 07:56 UTC, Cebion commented on ports/cognizance/Cognizance.sh
> +exec > >(tee "$GAMEDIR/log.txt") 2>&1
```suggestion
> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
```

2024-09-28 07:56 UTC, Cebion commented on ports/cognizance/port.json
> +      "aarch64"
```suggestion
      "armhf"
```

2024-09-28 08:26 UTC, kloptops approved these changes

2024-09-29 13:32 UTC, Cebion approved these changes

2024-09-29 13:32 UTC, merged