Added req: [analog_2] for ports which requires it
PortsMaster/PortMaster-New pull request #698
Opened 2024-09-28 15:00 UTC by Fraxinus88

Added req: [analog_2] for some of my ports which requires it

2024-09-28 16:42 UTC, JeodC commented
Do these definitely need *two* sticks, or is *one* permissible?

2024-09-29 03:18 UTC, Fraxinus88 commented
Definitely need twin sticks for these 4 games :)

2024-09-29 03:33 UTC, Slayer366 commented
I agree with adding this, but kloptops would be more suited to approving this particular addition to the port.json structure than I.

2024-09-29 03:36 UTC, kloptops requested changes
Needs fixes. 😬

2024-09-29 03:36 UTC, kloptops commented on ports/forgodden/port.json
> +    "reqs": [analog_2],
```suggestion
    "reqs": ["analog_2"],
```

2024-09-29 03:36 UTC, kloptops commented on ports/nulldrifter/port.json
> +    "reqs": [analog_2],
```suggestion
    "reqs": ["analog_2"],
```

2024-09-29 03:36 UTC, kloptops commented on ports/superraftboatclassic/port.json
> +    "reqs": [analog_2],
```suggestion
    "reqs": ["analog_2"],
```

2024-09-29 08:17 UTC, Fraxinus88 commented
Okies, committed the changes :)

2024-09-29 08:24 UTC, kloptops approved these changes

2024-09-29 08:31 UTC, merged