New port: LittleGPTracker
PortsMaster/PortMaster-New pull request #722
Opened 2024-10-02 18:14 UTC by ohol-vitaliy

# New Port for LittleGPTracker

## Game Information
- **Title**: LittleGPTracker
- **URL**: https://github.com/djdiskmachine/LittleGPTracker

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

2024-10-02 18:32 UTC, Cebion requested changes

2024-10-02 18:32 UTC, Cebion commented on ports/littlegptracker/port.json
Did you use our json generator?
https://portmaster.games/port-json.html

Because this is how the port.json needs to look like

```
{
  "version": 3,
  "name": "penguincommand.zip",
  "items": [
    "Penguin Command.sh",
    "penguincommand"
  ],
  "items_opt": [],
  "attr": {
    "title": "Penguin Command",
    "porter": [
      "Cebion"
    ],
    "desc": "This is a clone of the classic \"Missile Command\" Game, but it has better graphics and music. The gameplay has only been slightly modified.",
    "desc_md": null,
    "inst": "Ready to run! Beware that the Start of the game via R1 can take a second.",
    "inst_md": null,
    "genres": [
      "arcade"
    ],
    "image": null,
    "rtr": true,
    "exp": false,
    "runtime": null,
    "reqs": [],
    "arch": [
      "aarch64"
    ]
  }
}```

2024-10-03 08:34 UTC, Cebion commented on ports/littlegptracker/port.json
It's more looking for presence of the file at all I think :)

2024-10-05 08:40 UTC, Cebion submitted a review, later dismissed

2024-10-06 14:13 UTC, JeodC commented on ports/littlegptracker/LittleGPTracker.sh
> +source $controlfolder/device_info.txt
```suggestion
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
```

2024-10-06 14:16 UTC, JeodC requested changes

2024-10-06 14:16 UTC, JeodC commented on ports/littlegptracker/LittleGPTracker.sh
> +source $controlfolder/device_info.txt
```suggestion
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
```

2024-10-06 14:16 UTC, JeodC commented on ports/littlegptracker/LittleGPTracker.sh
> +$ESUDO kill -9 $(pidof gptokeyb)
```suggestion
pm_finish
```

2024-10-06 14:16 UTC, JeodC commented on ports/littlegptracker/LittleGPTracker.sh
> +$ESUDO systemctl restart oga_events &
```suggestion
```

2024-10-06 14:16 UTC, JeodC commented on ports/littlegptracker/README.md
> +D-Pad: In screen navigation.
This is really messy and hard to read. Look up how to use tables in markdown and/or look at how other readmes do it.

2024-10-06 14:16 UTC, JeodC commented on ports/littlegptracker/port.json
> +      "ohol-vitaliy"
Double check for a typo

2024-10-06 15:38 UTC, JeodC commented on ports/littlegptracker/port.json
> +      "ohol-vitaliy"
> Sorry, don't see typos in this file

Thought it might have been supposed to be `ohol-vitality`. If it's correct as is, np.

2024-10-06 17:32 UTC, JeodC approved these changes

2024-10-06 19:08 UTC, Cebion approved these changes

2024-10-06 19:08 UTC, merged