Update for iosas 1.02a
PortsMaster/PortMaster-New pull request #732
Opened 2024-10-03 22:40 UTC by JeodC

Update this port to use the latest Steam and Itch.io game version, 1.02a. Tested on RG552.

2024-10-03 23:01 UTC, JeodC commented
This PR requires the love patcher that is currently on the gui beta branch.

2024-10-05 02:41 UTC, Slayer366 approved these changes

2024-10-06 11:47 UTC, kloptops submitted a review, later dismissed

2024-10-06 15:14 UTC, cdeletre requested changes

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
> -source $controlfolder/device_info.txt
can be removed

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
> -$ESUDO chmod 666 /dev/tty1
can be removed

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
> -$ESUDO chmod 666 /dev/uinput
can be removed

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
> -    $ESUDO ./libs/splash "splash.png" 1
As it seems to only be needed in muOS maybe you can do this
```
[ "$CFW_NAME" == "muOS" ] && splash "splash.png" 1 # workaround for muOS
```

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
>  $ESUDO systemctl restart oga_events &
can be removed

2024-10-06 15:14 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
>  printf "\033c" > /dev/tty0
can be removed

2024-10-06 16:19 UTC, cdeletre requested changes

2024-10-06 16:19 UTC, cdeletre commented on ports/iosas/Isles of Sea and Sky.sh
> +pm_platform_helper "$GAMEDIR/gmloadernext.apk"
Almost ;)

2024-10-06 18:32 UTC, cdeletre approved these changes

2024-10-06 19:09 UTC, Cebion approved these changes

2024-10-06 19:09 UTC, merged