New Port: Phantasy Star RL
PortsMaster/PortMaster-New pull request #738
Opened 2024-10-06 09:27 UTC by Ganimoth

# New Port for Phantasy Star RL

## Game Information
- **Title**: Phantasy Star RL
- **URL**: https://requinnzious.itch.io/phantasy-star-rl

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-10-06 17:26 UTC, Slayer366 requested changes

2024-10-06 17:26 UTC, Slayer366 commented on ports/psrl/Phantasy Star RL.sh
> +$GPTOKEYB "gmloadernext" -c "psrl.gptk"&
```suggestion
$GPTOKEYB "gmloadernext" -c "psrl.gptk" &
```
I'm sure this was working, but I wonder if it'd be a good idea to put a space before the '&' so something goofy doesn't happen on another CFW/device...

2024-10-06 17:53 UTC, Slayer366 approved these changes

2024-10-06 19:16 UTC, Cebion requested changes

2024-10-06 19:16 UTC, Cebion commented on ports/psrl/Phantasy Star RL.sh
> +$ESUDO chmod 666 /dev/uinput
```suggestion
```

2024-10-06 19:16 UTC, Cebion commented on ports/psrl/Phantasy Star RL.sh
> +
```suggestion
pm_platform_helper "$GAMEDIR/gmloadernext"
```

2024-10-06 19:26 UTC, Cebion requested changes

2024-10-06 19:26 UTC, Cebion commented on ports/psrl/Phantasy Star RL.sh
> +pm_platform_helper "$GAMEDIR/gmloadernext"
```suggestion
```

2024-10-06 19:26 UTC, Cebion commented on ports/psrl/Phantasy Star RL.sh
> +$GPTOKEYB "gmloadernext" -c "psrl.gptk" &
```suggestion
$GPTOKEYB "gmloadernext" -c "psrl.gptk" &
pm_platform_helper "$GAMEDIR/gmloadernext"
```

2024-10-06 19:27 UTC, Cebion commented on ports/psrl/Phantasy Star RL.sh
> +$GPTOKEYB "gmloadernext" -c "psrl.gptk" &
Switched pm_platform_helper to after gptokeyb

2024-10-07 08:17 UTC, Cebion approved these changes

2024-10-07 14:13 UTC, JanTrueno approved these changes
👍

2024-10-07 14:13 UTC, merged