New Port Goblin Dungeoneer
PortsMaster/PortMaster-New pull request #739
Opened 2024-10-06 13:55 UTC by Fraxinus88

# New Port for Goblin Dungeoneer

## Game Information
- **Title**: Goblin Dungeoneer
- **URL**: https://crackedghostgames.itch.io/goblin-dungeoneer

## Submission Requirements

### CFW Tests
[X] AmberELEC
[X] ArkOS
[X] JELOS/ROCKNIX
[X] MuOS

Architecture
[X] armHF
[X] Panfrost (Mainline)

Resolution Tests
Test all major resolutions:
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-06 17:35 UTC, Slayer366 submitted a review, later dismissed

2024-10-06 19:14 UTC, Cebion requested changes

2024-10-06 19:14 UTC, Cebion commented on ports/goblindungeoneer/Goblin Dungeoneer.sh
> +source $controlfolder/device_info.txt
```suggestion
```

2024-10-06 19:14 UTC, Cebion commented on ports/goblindungeoneer/Goblin Dungeoneer.sh
> +$ESUDO chmod 666 /dev/tty0
```suggestion
```

2024-10-06 19:14 UTC, Cebion commented on ports/goblindungeoneer/Goblin Dungeoneer.sh
> +
```suggestion
pm_platform_helper "$GAMEDIR/gmloader"
```

2024-10-06 19:14 UTC, Cebion commented on ports/goblindungeoneer/Goblin Dungeoneer.sh
> +$ESUDO kill -9 $(pidof gptokeyb)
```suggestion
```

2024-10-06 19:14 UTC, Cebion commented on ports/goblindungeoneer/Goblin Dungeoneer.sh
> +$ESUDO systemctl restart oga_events &
```suggestion
pm_finish
```

2024-10-07 00:11 UTC, Fraxinus88 commented
Changes committed :)

2024-10-07 14:11 UTC, JanTrueno approved these changes

2024-10-07 14:11 UTC, JanTrueno commented on ports/goblindungeoneer/goblindungeoneer/patch/Patch Notes.txt
Gotta be somewhat careful with adding original code in patchnotes, but this is simple enough thats its probably fine.

2024-10-07 18:18 UTC, Cebion approved these changes

2024-10-07 18:18 UTC, merged