Multi Players Manic Miner
PortsMaster/PortMaster-New pull request #75
Opened 2024-02-10 15:50 UTC by monkeyx-net

new file:   ports/multimanicminer/README.md
	new file:   ports/multimanicminer/multimanicminer/conf/pulse/cookie
	new file:   ports/multimanicminer/multimanicminer/multimanicminer.gptk
	new file:   ports/multimanicminer/multimanicminer/multimanicminer.pck
	new file:   ports/multimanicminer/multimanicminer/multimanicminer_LICENSE.txt
	new file:   ports/multimanicminer/port.json
	new file:   ports/multimanicminer/screenshot.png

# New Port for Multi Players Manic Miner

## Game Information
- **Title**: Multi Players Manic Miner
- **URL**: https://github.com/SteveSmith16384/ManicMinerMultiplayer

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ x] AmberELEC
- [x ] ArkOS
- [x ] JELOS

### Resolution Tests
Test all major resolutions:
- [ x] 480x320
- [ x] 640x480
- [ x] 720x720 (RGB30)
- [ x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-02-10 20:46 UTC, Cebion submitted a review, later dismissed
👍

2024-02-11 02:47 UTC, kloptops commented on ports/multimanicminer/README.md
> +Thanks to [Steven Smith]https://github.com/SteveSmith16384/ManicMinerMultiplayer for this game.
Markdown is wrong. it should be

```markdown
Thanks to [Steven Smith](https://github.com/SteveSmith16384/ManicMinerMultiplayer) for this 
```

2024-02-11 02:48 UTC, kloptops requested changes
Markdown needs a fix.

2024-02-11 08:04 UTC, monkeyx-net commented
> Markdown needs a fix.

Hopefully I managed to do this on my phone.

2024-02-12 08:36 UTC, kloptops approved these changes
👍

2024-02-12 08:54 UTC, Cebion approved these changes

2024-02-12 08:54 UTC, merged