New Port: Hawk Island
PortsMaster/PortMaster-New pull request #751
Opened 2024-10-08 12:16 UTC by Ganimoth

# New Port for Hawk Island

## Game Information
- **Title**: Hawk Island
- **URL**: https://lutd.itch.io/hawk-island

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x ] AmberELEC
- [x ] ArkOS
- [x ] ROCKNIX
- [x ] muOS

### Resolution Tests
Test all major resolutions:
- [x ] 480x320
- [x ] 640x480
- [ ] 720x720 (RGB30)
- [x ] Higher resolutions (e.g., 1280x720)

2024-10-08 12:33 UTC, Ganimoth commented
As I just noticed in another ongoing PR, do we still need printf "\033c" > /dev/tty0?

2024-10-08 12:36 UTC, Cebion commented
> As I just noticed in another ongoing PR, do we still need printf "\033c" > /dev/tty0?

Not anymore

2024-10-08 12:39 UTC, Cebion submitted a review, later dismissed

2024-10-08 13:28 UTC, cdeletre requested changes

2024-10-08 13:28 UTC, cdeletre commented on ports/hawkisland/Hawk Island.sh
> +./gmloadernext game.apk
gmloadernext doesn't use this command line argument to load the apk, it's always game.apk. (see [here](https://github.com/JohnnyonFlame/gmloader-next/blob/6f2569914109866c1fb903a9b7aed970896b5618/gmloader/main.cpp#L83))
```suggestion
./gmloadernext
```

2024-10-08 13:28 UTC, cdeletre commented on ports/hawkisland/hawkisland/game.apk
The file needs some cleaning, please remove:
- AndroidManifest.xml
- androidsupportmultidexversion.txt
- classes.dex
- META-INF/*
- res/*
- resources.arsc

To do so you can run
`zip -d game.apk AndroidManifest.xml androidsupportmultidexversion.txt classes.dex "res/*" "META-INF/*  resources.arsc"`

I let you check that the game still runs but it should be ok.

2024-10-08 15:02 UTC, Ganimoth commented on ports/hawkisland/hawkisland/game.apk
Done, game seems to be still working fine.

2024-10-09 09:55 UTC, Cebion submitted a review, later dismissed

2024-10-09 12:35 UTC, cdeletre submitted a review, later dismissed

2024-10-09 17:55 UTC, Cebion approved these changes

2024-10-09 17:57 UTC, cdeletre approved these changes

2024-10-09 19:18 UTC, merged