New Port for Techmaniac
PortsMaster/PortMaster-New pull request #758
Opened 2024-10-09 17:16 UTC by Ganimoth

**New Port for Techmaniac**

Game Information
Title: Techmaniac
URL: https://johngabrieluk.itch.io/techmaniac

CFW Tests

**Ensure your game has been tested on all major CFWs:**

[x ] AmberELEC
[x ] ArkOS
[x ] ROCKNIX
[x ] muOS

**Resolution Tests**

Test all major resolutions:
[x ] 480x320
[x ] 640x480
[  ] 720x720 (RGB30)
[x ] Higher resolutions (e.g., 1280x720)

2024-10-09 18:17 UTC, cdeletre requested changes

2024-10-09 19:18 UTC, Cebion requested changes

2024-10-09 19:18 UTC, Cebion commented on ports/techmaniac/Techmaniac.sh
> +pm_platform_helper "$runtime"
duplicate

2024-10-09 19:18 UTC, Cebion commented on ports/techmaniac/Techmaniac.sh
> +pm_platform_helper "$runtime"
```suggestion
```

2024-10-09 21:42 UTC, cdeletre approved these changes

2024-10-10 09:01 UTC, Cebion approved these changes

2024-10-10 09:55 UTC, JanTrueno approved these changes

2024-10-10 09:56 UTC, merged