New Port: Pachi el Marciano
PortsMaster/PortMaster-New pull request #768
Opened 2024-10-10 20:17 UTC by Cebion

Game Information
Title: Pachi el Marciano
URL: https://sourceforge.net/projects/dragontech/

| Button | Action |
|--|--| 
|DPAD| Move|
|A | Jump|

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS
[X] Knulli (Optional)
[] Crossmix (Optional)

Architectures: 
[x] Aarch64
[X] Panfrost (Mainline)

Resolutions: 
[] 480x320 (Optional)
[X] 640x480
[] 720x720 (RGB30) (Optional)
[X] Higher resolutions (e.g., 1280x720)

2024-10-10 21:09 UTC, tabreturn reviewed
See comments

2024-10-10 21:09 UTC, tabreturn commented on ports/pachi/gameinfo.xml
shouldn't it be? when this is made --> when this is met

2024-10-10 21:09 UTC, tabreturn commented on ports/pachi/port.json
- Remove the \n symbols in the desc? These seem oddly placed.
- Pachi el marciano is a platforms game --> Pachi el marciano is a platform game
- when this is\nmade --> when this is met

2024-10-10 22:12 UTC, cdeletre submitted a review, later dismissed

2024-10-11 07:31 UTC, tabreturn approved these changes

2024-10-11 08:53 UTC, kloptops requested changes

2024-10-11 08:53 UTC, kloptops commented on ports/pachi/gameinfo.xml
> +met, the exit gate to the next stage will appear and you can pass trough.</desc>
```suggestion
met, the exit gate to the next stage will appear and you can pass through.</desc>
```

2024-10-11 08:53 UTC, kloptops commented on ports/pachi/port.json
> +    "desc": "Pachi el marciano is a platform game inspired by games like Manic Miner and Jet Set Willy from the legend Mathew Smith. The goal of the game is to collect all the objects of each level,
```suggestion
    "desc": "Pachi el marciano is a platform game inspired by games like Manic Miner and Jet Set Willy from the legend Mathew Smith. The goal of the game is to collect all the objects of each level, when this is met, the exit gate to the next stage will appear and you can pass through.",
```

2024-10-11 12:21 UTC, kloptops approved these changes

2024-10-11 17:29 UTC, cdeletre approved these changes

2024-10-11 18:37 UTC, merged