New Port - Powerputt Legend
PortsMaster/PortMaster-New pull request #782
Opened 2024-10-13 23:41 UTC by steventrev

# New Port for Powerputt Legend

## Game Information
- **Title**: Powerputt Legend
- **URL**: https://team-bugulon.itch.io/powerputt-legend

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-10-14 07:11 UTC, kloptops requested changes
Small change otherwise looks good. Is it `PowerPutt Legend` or `Powerputt Legend`?

It's a bit inconsistent in the `port.json` and `gameinfo.xml`. :)

2024-10-14 07:11 UTC, kloptops commented on ports/powerputtlegend/gameinfo.xml
> +    <image>./PowerPuttLegend/screenshot.jpg</image>
Wrong case in path.

```suggestion
    <image>./powerputtlegend/screenshot.jpg</image>
```

2024-10-14 11:30 UTC, JeodC requested changes

2024-10-14 11:30 UTC, JeodC commented on ports/powerputtlegend/port.json
> +      "armhf"
This is using gmloadernext, so it's aarch64.

2024-10-14 11:30 UTC, JeodC commented on ports/powerputtlegend/cover.jpg
I think images need to be .png format, but this could be wrong.

2024-10-14 13:48 UTC, steventrev commented on ports/powerputtlegend/cover.jpg
Happy to change, but should also modify PortMaster-New readme:

2024-10-14 13:53 UTC, steventrev commented on ports/powerputtlegend/cover.jpg
I can change, would also need revision of sources that reference cover.jpg:

- https://github.com/PortsMaster/PortMaster-New?tab=readme-ov-file#new-port-structure

- https://portmaster.games/packaging.html

2024-10-14 14:19 UTC, JeodC approved these changes

2024-10-15 07:41 UTC, Cebion requested changes

2024-10-15 07:41 UTC, Cebion commented on ports/powerputtlegend/README.md
> +Thanks [Team Bugulon](https://team-bugulon.itch.io/) for creating this game and allowing us to distribute it!
Missing URL to the Game.

2024-10-15 07:41 UTC, Cebion commented on ports/powerputtlegend/port.json
> +    "rtr": true,
rtr:true means gamedata is included.
If that is the case a license needs also to be provided.

2024-10-15 13:18 UTC, cdeletre commented on ports/powerputtlegend/Powerputt Legend.sh
> +./gmloadernext game.apk
gmloadernext doesn't use the command line argument, `game.apk` can be remove in this line.
```suggestion
./gmloadernext
```

2024-10-15 13:23 UTC, cdeletre commented on ports/powerputtlegend/Powerputt Legend.sh
> +$ESUDO ./libs/splash "splash.png" 1
This is a workaround for muOS so it's better to use it only when muOS is detected
```suggestion
[ "$CFW_NAME" == "muOS" ] && splash "splash.png" 1 # workaround for muOS
```

2024-10-15 17:19 UTC, steventrev commented on ports/powerputtlegend/gameinfo.xml
> +    <path>./PowerPutt Legend.sh</path>
Thanks! Casing needed explicit `git mv "Powerputt Legend.sh" "PowerPutt Legend.sh"` to be recognized. Probably Windows related.

2024-10-15 17:21 UTC, steventrev commented on ports/powerputtlegend/Powerputt Legend.sh
> +export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/libs:$LD_LIBRARY_PATH"
Libs folder added to support ArkOS in [c8c5d6e](https://github.com/PortsMaster/PortMaster-New/pull/782/commits/c8c5d6e3e518997d495a0401143bfc458bbbcd8d).

2024-10-15 17:26 UTC, cdeletre approved these changes

2024-10-15 17:32 UTC, steventrev commented on ports/powerputtlegend/gameinfo.xml
> +    <path>./PowerPutt Legend.sh</path>
It appears this casing change still did not take on the latest commit. Will try again.

2024-10-15 17:36 UTC, cdeletre submitted a review, later dismissed

2024-10-15 17:37 UTC, cdeletre requested changes

2024-10-15 17:37 UTC, cdeletre commented on ports/powerputtlegend/20240307_TeamBugulon-DistributionAgreement.png
This file goes into `ports/powerputtlegend/powerputtlegend/`

2024-10-15 17:43 UTC, cdeletre submitted a review, later dismissed

2024-10-15 18:40 UTC, JeodC approved these changes

2024-10-15 21:18 UTC, merged