Sonic TT 16-Bit: Refactor port
PortsMaster/PortMaster-New pull request #794
Opened 2024-10-15 23:33 UTC by JeodC

- Do texture repacking and audio compression
- Only source from 64bit apk (no more 32bit)
- Use newer gmloadernext
- Fix controls for TSP

2024-10-16 02:16 UTC, cdeletre approved these changes

2024-10-16 02:16 UTC, cdeletre commented on ports/sonictt16b/Sonic Triple Trouble - 16-Bit.sh
> +    $ESUDO ./libs/splash "splash.png" 1
```suggestion
[ "$CFW_NAME" == "muOS" ] && $ESUDO ./libs/splash "splash.png" 1 
```

2024-10-16 02:16 UTC, cdeletre commented on ports/sonictt16b/Sonic Triple Trouble - 16-Bit.sh
> +./gmloadernext game.apk
Does your build use the `game.apk` argument ?

2024-10-16 11:53 UTC, Cebion requested changes
see comments from @cdeletre

2024-10-16 12:24 UTC, cdeletre requested changes
See my request changes :)

2024-10-16 13:25 UTC, cdeletre commented on ports/sonictt16b/Sonic Triple Trouble - 16-Bit.sh
> +./gmloadernext game.apk
I've checked on your UFO 50 port and it indeed doesn't use it :)

2024-10-16 13:26 UTC, cdeletre requested changes

2024-10-16 13:26 UTC, cdeletre commented on ports/sonictt16b/Sonic Triple Trouble - 16-Bit.sh
> +./gmloadernext game.apk
```suggestion
./gmloadernext
```

2024-10-16 14:36 UTC, cdeletre approved these changes

2024-10-17 07:15 UTC, Cebion approved these changes

2024-10-20 12:59 UTC, merged