Super Skelemania
PortsMaster/PortMaster-New pull request #798
Opened 2024-10-16 08:09 UTC by tabreturn

# New Port for Super Skelemania

## Game Information
- **Title**: Super Skelemania
- **URL**: https://benal.itch.io/super-skelemania

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-16 10:24 UTC, kloptops submitted a review, later dismissed

2024-10-16 11:48 UTC, Cebion requested changes

2024-10-16 11:48 UTC, Cebion commented on ports/superskelemania/Super Skelemania.sh
> +export PORT_32BIT="Y"
Has to be before mod_cfw line

2024-10-16 11:48 UTC, Cebion commented on ports/superskelemania/Super Skelemania.sh
> +pm_platform_helper $GAMEDIR/gmloader
```suggestion
pm_platform_helper "$GAMEDIR/gmloader"
```

2024-10-16 11:48 UTC, Cebion commented on ports/superskelemania/port.json
> +      "aarch64"
gmloader is 32 bit
```suggestion
      "armhf"
```

2024-10-16 12:39 UTC, cdeletre requested changes

2024-10-16 12:39 UTC, cdeletre commented on ports/superskelemania/superskelemania/game.apk
Remove this files from the apk

```
unzip -l game.apk
Archive:  game.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-14-2024 20:32   lib/
        0  02-14-2024 20:32   lib/armeabi/
   312924  02-14-2024 20:32   lib/armeabi/libopenal.so
  4878276  02-14-2024 20:32   lib/armeabi/libyoyo.so
        0  02-14-2024 20:32   lib/armeabi-v7a/
   288356  02-14-2024 20:32   lib/armeabi-v7a/libopenal.so
  4689844  02-14-2024 20:32   lib/armeabi-v7a/libyoyo.so
        0  02-14-2024 20:32   lib/mips/
   414556  02-14-2024 20:32   lib/mips/libopenal.so         <=====
  6718636  02-14-2024 20:32   lib/mips/libyoyo.so           <=====
        0  02-14-2024 20:32   lib/x86/
   316964  02-14-2024 20:32   lib/x86/libopenal.so          <=====
  5943740  02-14-2024 20:32   lib/x86/libyoyo.so            <=====
---------                     -------
 23563296                     13 files
```

2024-10-16 21:37 UTC, tabreturn commented on ports/superskelemania/superskelemania/game.apk
Done. Thx

2024-10-16 21:37 UTC, tabreturn commented on ports/superskelemania/Super Skelemania.sh
> +export PORT_32BIT="Y"
Done. Thx

2024-10-17 07:14 UTC, Cebion approved these changes

2024-10-17 09:46 UTC, kloptops approved these changes

2024-10-17 12:13 UTC, merged