Halloween Forever
PortsMaster/PortMaster-New pull request #800
Opened 2024-10-16 08:55 UTC by tabreturn

# New Port for { Game Title }

## Game Information
- **Title**: Halloween Forever
- **URL**: https://imaginarymonsters.itch.io/halloween-forever

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-16 10:29 UTC, kloptops requested changes

2024-10-16 10:29 UTC, kloptops commented on ports/halloweenforever/Halloween Forever.sh
> +export PORT_32BIT="Y"
This should be before `mod_${CFW_NAME}.txt` 

```suggestion
export PORT_32BIT="Y"
```

2024-10-16 10:29 UTC, kloptops commented on ports/halloweenforever/Halloween Forever.sh
> +[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
```suggestion
export PORT_32BIT="Y"
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
```

2024-10-16 11:19 UTC, kloptops submitted a review, later dismissed

2024-10-16 11:45 UTC, Cebion requested changes

2024-10-16 11:45 UTC, Cebion commented on ports/halloweenforever/Halloween Forever.sh
> +pm_platform_helper $GAMEDIR/gmloader
```suggestion
pm_platform_helper "$GAMEDIR/gmloader"
```

2024-10-16 11:45 UTC, Cebion commented on ports/halloweenforever/port.json
> +      "aarch64"
Gmloader is 32 bit
```suggestion
      "armhf"
```

2024-10-16 12:35 UTC, cdeletre requested changes

2024-10-16 12:35 UTC, cdeletre commented on ports/halloweenforever/halloweenforever/halloweenforever.apk
remove these files from the apk :)

```
unzip -l halloweenforever.apk
Archive:  halloweenforever.apk
  Length      Date    Time    Name
---------  ---------- -----   ----
     5472  00-00-1980 00:00   AndroidManifest.xml                <=====
     1361  00-00-1980 00:00   META-INF/CERT.RSA                  <=====
     1877  00-00-1980 00:00   META-INF/CERT.SF                   <=====
     1834  00-00-1980 00:00   META-INF/MANIFEST.MF               <=====
  1406608  00-00-1980 00:00   classes.dex                        <=====
  4772484  00-00-1980 00:00   lib/armeabi-v7a/libyoyo.so
  4969108  00-00-1980 00:00   lib/armeabi/libyoyo.so
  6850476  00-00-1980 00:00   lib/mips/libyoyo.so                <=====
  6055484  00-00-1980 00:00   lib/x86/libyoyo.so                 <=====
      244  00-00-1980 00:00   res/drawable-hdpi-v4/icon.png      <=====
      217  00-00-1980 00:00   res/drawable-ldpi-v4/icon.png      <=====
      228  00-00-1980 00:00   res/drawable-mdpi-v4/icon.png      <=====
      270  00-00-1980 00:00   res/drawable-xhdpi-v4/icon.png     <=====
      323  00-00-1980 00:00   res/drawable-xxhdpi-v4/icon.png    <=====
      392  00-00-1980 00:00   res/drawable-xxxhdpi-v4/icon.png.  <=====
      270  00-00-1980 00:00   res/drawable/icon.png              <=====
     5072  00-00-1980 00:00   res/layout/download.xml            <=====
      808  00-00-1980 00:00   res/layout/main.xml                <=====
     1528  00-00-1980 00:00   res/layout/userpasslayout.xml      <=====
     1040  00-00-1980 00:00   res/xml/preferences.xml            <=====
     5448  00-00-1980 00:00   resources.arsc                     <=====
---------                     -------
 24080544                     21 files
```

2024-10-16 21:30 UTC, tabreturn commented on ports/halloweenforever/halloweenforever/halloweenforever.apk
Thanks. Done.

2024-10-17 07:14 UTC, Cebion approved these changes

2024-10-17 09:47 UTC, kloptops approved these changes

2024-10-17 12:13 UTC, merged