New Port: Gato Roboto
PortsMaster/PortMaster-New pull request #809
Opened 2024-10-19 13:13 UTC by JanTrueno

# New Port for Gato Roboto

## Game Information
- **Title**: Gato Roboto
- **URL**: https://www.gog.com/en/game/gato_roboto

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS
- [X] Crossmix

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-19 20:56 UTC, cdeletre requested changes

2024-10-19 20:56 UTC, cdeletre commented on ports/gatoroboto/Gato Roboto.sh
> +    $ESUDO ./tools/splash "splash.png" 1
```suggestion
    [ "$CFW_NAME" == "muOS" ] && $ESUDO splash "splash.png" 1 # workaround for muOS
```

2024-10-19 21:39 UTC, cdeletre approved these changes

2024-10-20 13:32 UTC, Cebion approved these changes

2024-10-20 13:32 UTC, merged