New Port: Guacamelee
PortsMaster/PortMaster-New pull request #817
Opened 2024-10-20 19:33 UTC by Cebion

Game Information
Title: Guacamelee
URL: https://www.gog.com/en/game/guacamelee_gold_edition / Humble Bundle Version

Instructions
Add your Linux Guacamelee_DRMFREE.sh, (not sure what the name from GOG is) to the guacamelee folder and run the game.

Else extract the archive and place the game-bin and the resource files to the guacamelee/gamedata folder

(Autoinstaller for Guacamelee_DRMFREE.sh included)

Tested with Guacamelee_DRMFREE.sh from Humble

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS
[] Knulli (Optional)
[] Crossmix (Optional)

Architectures: 
[X] Aarch64
[X] Panfrost (Mainline)

Resolutions: 
[] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30) (Optional)
[X] Higher resolutions (e.g., 1280x720) 

I excluded RK3326, because the performance is abmyssal

2024-10-20 19:54 UTC, cdeletre requested changes

2024-10-20 19:54 UTC, cdeletre commented on ports/guacamelee/README.md
> +Speical thanks to kotzebuedog for solving a game-breaking bug
```suggestion
Special thanks to kotzebuedog for solving a game-breaking bug
```

2024-10-21 00:10 UTC, cdeletre approved these changes

2024-10-21 00:30 UTC, Slayer366 approved these changes

2024-10-21 06:22 UTC, merged