Somnokid
PortsMaster/PortMaster-New pull request #823
Opened 2024-10-21 15:48 UTC by slobters

# New Port for Somnokid

## Game Information
- **Title**: Somnokid
- **URL**: https://team-bugulon.itch.io/somnokid

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [X] 640x480
- [ ] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-21 15:52 UTC, slobters commented on ports/somnokid/Somnokid.sh
Removed "TOOLDIR="$GAMEDIR/tools" " and line at the end

2024-10-22 01:48 UTC, cdeletre requested changes
You can also add these licenses:
* [LICENSE.libcrypto.txt](https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libcrypto.txt)
* [LICENSE.libopenal.txt](https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libopenal.txt)
* [LICENSE.libzip.txt](https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libzip.txt)

2024-10-22 01:48 UTC, cdeletre commented on ports/somnokid/Somnokid.sh
> +pm_platform_helper $GAMEDIR/gmloadernext
```suggestion
pm_platform_helper "$GAMEDIR/gmloadernext"
```

2024-10-22 01:48 UTC, cdeletre commented on ports/somnokid/Somnokid.sh
> +$ESUDO ./tools/splash "splash.png" 10000 &
`splash` is in the `PATH` :)
```suggestion
$ESUDO splash "splash.png" 10000 &
```

2024-10-22 01:48 UTC, cdeletre commented on ports/somnokid/Somnokid.sh
> +export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/libs:$LD_LIBRARY_PATH"
As discussed with Cebion in [PR 818](https://github.com/PortsMaster/PortMaster-New/pull/818#discussion_r1808166816) it's better and easier in the long run.

Don't forget to also rename the `libs` folder to `libs.aarch64`

```suggestion
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
```

2024-10-22 07:41 UTC, Cebion approved these changes

2024-10-22 11:30 UTC, cdeletre approved these changes

2024-10-22 12:53 UTC, merged