New port: Mini Doom II
PortsMaster/PortMaster-New pull request #831
Opened 2024-10-22 15:34 UTC by cdeletre

# New Port for Mini Doom II

## Game Information
- **Title**: Mini Doom II
- **URL**: [minidoom2](https://calaverastudio.itch.io/minidoom2)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS
- [x] Knulli (Optional)
- [x] Crossmix (Optional)

### Architectures: 
- [x] Aarch64
- [x] Panfrost (Mainline)

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure

```
.
├── Mini Doom II.sh
├── README.md
├── cover.png
├── gameinfo.xml
├── minidoom2
│   ├── LICENSE.libcrypto.txt
│   ├── LICENSE.libflac.txt
│   ├── LICENSE.libogg.txt
│   ├── LICENSE.libopenal.txt
│   ├── LICENSE.libvorbis.txt
│   ├── LICENSE.libvorbisenc.txt
│   ├── LICENSE.libzip.txt
│   ├── SDL_swap_gpbuttons.txt
│   ├── config.json
│   ├── default-configs.ini
│   ├── gamedata
│   ├── gmloadernext
│   ├── lib
│   │   └── arm64-v8a
│   │       ├── libc++_shared.so
│   │       ├── libcompiler_rt.so
│   │       └── libm.so
│   ├── libs.aarch64
│   │   ├── libcrypto.so.1.1
│   │   ├── libopenal.so.1
│   │   └── libzip.so.5
│   ├── minidoom2.apk
│   ├── splash.png
│   └── tools
│       ├── Klib
│       │   └── GMblob.py
│       ├── SDL_swap_gpbuttons.py
│       ├── install_minidoom2
│       ├── libs.aarch64
│       │   ├── libFLAC.so.8
│       │   ├── libogg.so.0
│       │   ├── libvorbis.so.0
│       │   └── libvorbisenc.so.2
│       ├── misc.zip
│       ├── oggdec
│       ├── oggenc
│       ├── splash
│       ├── vgmstream-cli
│       └── wwise2audiogroup.py
├── port.json
└── screenshot.png
```

2024-10-22 17:29 UTC, Cebion requested changes

2024-10-22 17:29 UTC, Cebion commented on ports/minidoom2/Mini Doom II.sh
> +#$GPTOKEYB "gmloader" -c ./minidoom2.gptk &
Obosolete line?

2024-10-22 17:33 UTC, cdeletre commented on ports/minidoom2/Mini Doom II.sh
> +#$GPTOKEYB "gmloader" -c ./minidoom2.gptk &
yep, indeed. I'll remove it :)

2024-10-23 05:47 UTC, Slayer366 approved these changes

2024-10-23 07:29 UTC, Cebion approved these changes

2024-10-23 07:29 UTC, merged