Jump on Head
PortsMaster/PortMaster-New pull request #844
Opened 2024-10-24 10:44 UTC by tabreturn

# New Port for Jump on Head

## Game Information
- **Title**: Jump on Head
- **URL**: https://organzola.itch.io/jumponhead

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-24 13:38 UTC, cdeletre requested changes
How about a nice cover ? :)

![jumponhead](https://github.com/user-attachments/assets/6bfc5356-ea66-4ea5-8df6-e9500c4c5cc6)

2024-10-24 13:38 UTC, cdeletre commented on ports/jumponhead/jumponhead/libs/libzip.so.5
You can add the license https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libzip.txt

2024-10-24 13:38 UTC, cdeletre commented on ports/jumponhead/jumponhead/libs/libcrypto.so.1.1
You can add the license https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libcrypto.txt

2024-10-24 20:51 UTC, tabreturn commented on ports/jumponhead/jumponhead/libs/libzip.so.5
Thx. done :)

2024-10-24 23:40 UTC, cdeletre approved these changes

2024-10-25 08:13 UTC, Cebion approved these changes

2024-10-25 08:14 UTC, merged