Splinter Zone
PortsMaster/PortMaster-New pull request #845
Opened 2024-10-24 10:45 UTC by tabreturn

# New Port for Splinter Zone

## Game Information
- **Title**: Splinter Zone
- **URL**: https://mokka.itch.io/splinter-zone

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-24 16:29 UTC, cdeletre requested changes
How about a nice cover ? :)
![splinterzone-fs8](https://github.com/user-attachments/assets/720ec813-c585-47d8-b993-32ad1dc7d3b5)

2024-10-24 16:29 UTC, cdeletre commented on ports/splinterzone/splinterzone/libs/libcrypto.so.1.1
Please add https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libcrypto.txt

2024-10-24 16:29 UTC, cdeletre commented on ports/splinterzone/splinterzone/libs/libzip.so.5
Please add https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libzip.txt

2024-10-24 20:52 UTC, tabreturn commented on ports/splinterzone/splinterzone/libs/libcrypto.so.1.1
Thx. done :)

2024-10-24 20:52 UTC, tabreturn commented on ports/splinterzone/splinterzone/libs/libzip.so.5
Thx. done :)

2024-10-24 23:40 UTC, cdeletre approved these changes

2024-10-25 08:12 UTC, Cebion approved these changes

2024-10-25 08:13 UTC, merged