New Port: Yar's Revenge
PortsMaster/PortMaster-New pull request #850
Opened 2024-10-25 08:08 UTC by Cebion

Game Information
Title: Yar's Revenge
URL: www.autismuk.freeserve.co.uk/index.htm
https://github.com/Cebion/yars_revenge

Controls

| Button | Action |
|--|--| 
|DPAD| Steer|
|A/B | Shoot|

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS
[x] Knulli (Optional)
[] Crossmix (Optional)

Architectures: 
[x] Aarch64
[X] Panfrost (Mainline)

Resolutions: 
[X] 480x320 (Optional)
[X] 640x480
[X] 720x720  (Optional)
[X] Higher resolutions (e.g., 1280x720)

2024-10-25 12:53 UTC, JanTrueno submitted a review, later dismissed

2024-10-25 17:20 UTC, cdeletre commented on ports/yarsrevenge/README.md
> +Thanks to [Paul Robson](www.autismuk.freeserve.co.uk/index.htm) for making this game and releasing it for free.
The link doesn't seem to work

2024-10-25 17:49 UTC, cdeletre requested changes
![yarsrevenge-fs8](https://github.com/user-attachments/assets/4a589e22-3bd0-4103-9122-72ee3ae0c3a8)
:)

2024-10-26 17:33 UTC, cdeletre approved these changes

2024-10-27 13:11 UTC, merged