3D Space Pinball Cadet: update binary, launch script and add gptk map…
PortsMaster/PortMaster-New pull request #852
Opened 2024-10-25 14:50 UTC by cdeletre

update binary, launch script and add gptk map

2024-10-25 14:53 UTC, cdeletre commented
I've updated the port in my minidoom2 branch, don't try to understand why ;)

2024-10-25 14:54 UTC, Cebion submitted a review, later dismissed

2024-10-25 19:37 UTC, Slayer366 requested changes

2024-10-25 19:37 UTC, Slayer366 commented on ports/space.cadet.pinball/Space Cadet Pinball.sh
> +# PORTMASTER: space.cadet.pinball.zip, Space Cadet Pinball.sh
```suggestion
```

2024-10-26 16:40 UTC, JeodC approved these changes

2024-10-26 16:42 UTC, Cebion approved these changes

2024-10-26 16:42 UTC, merged