New Port Skeleton Boomerang
PortsMaster/PortMaster-New pull request #853
Opened 2024-10-25 16:37 UTC by Fraxinus88

# New Port for Skeleton Boomerang

## Game Information
- **Title**: Skeleton Boomerang
- **URL**: https://store.steampowered.com/app/658150/Skeleton_Boomerang/

## Submission Requirements
CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] JELOS/ROCKNIX
[X] MuOS

Architecture
[X] armHF
[X] Panfrost (Mainline)

Resolution Tests
Test all major resolutions:
[X] 480x320
[X] 640x480
[X] 720x720 (RGB30)
[X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-25 17:07 UTC, cdeletre requested changes

2024-10-25 17:07 UTC, cdeletre commented on ports/skeletonboomerang/cover.png
![skeletonboomerang-fs8](https://github.com/user-attachments/assets/59fdb710-71cf-4cc1-bac8-c5c4d64ddeac)

;)

2024-10-25 17:07 UTC, cdeletre commented on ports/skeletonboomerang/skeletonboomerang/libs/libcrypto.so.1.1
I know we don't like administrative tasks ;)
https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libcrypto.txt

2024-10-25 17:07 UTC, cdeletre commented on ports/skeletonboomerang/skeletonboomerang/libs/libzip.so.4
https://github.com/cdeletre/PortMaster-MiniDoom2/blob/main/minidoom2/LICENSE.libzip.txt

2024-10-26 05:59 UTC, Fraxinus88 commented on ports/skeletonboomerang/port.json
> +    "skeletonboomerang"
Whoopsies

2024-10-26 06:02 UTC, Fraxinus88 commented on ports/skeletonboomerang/cover.png
Awesome!

2024-10-26 16:42 UTC, Cebion approved these changes

2024-10-26 17:33 UTC, cdeletre approved these changes

2024-10-27 13:12 UTC, merged