Free Gish
PortsMaster/PortMaster-New pull request #858
Opened 2024-10-26 16:53 UTC by Cebion

Game Information
Title: Free Gish
URL: https://github.com/freegish/freegish

Controls

| Button | Action |
|--|--| 
|DPAD| Steer|
|A | Stick|
|B | Jump|
|X | Heavy|
|Y | Slide|
|L1/R1 | Y/N|
|L2 | C (Continue)|
|R2 | P (Practice)|

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] ROCKNIX
[X] MuOS
[X] Knulli (Optional)
[] Crossmix (Optional)

Architectures: 
[x] Aarch64
[X] Panfrost (Mainline)

Resolutions: 
[] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30) (Optional)
[X] Higher resolutions (e.g., 1280x720)

2024-10-27 00:55 UTC, tabreturn reviewed
Is Yar's Revenge supposed to be bundled with this PR?

2024-10-27 13:28 UTC, Cebion commented
> Is Yar's Revenge supposed to be bundled with this PR?

Whoops, fixed. That happens if you don't switch to branch main first :P

2024-10-27 18:24 UTC, cdeletre requested changes

2024-10-27 18:24 UTC, cdeletre commented on ports/freegish/port.json
> +    "title": "Gish",
```suggestion
    "title": "Free Gish",
```

2024-10-27 18:24 UTC, cdeletre commented on ports/freegish/gameinfo.xml
> +    <image>./freegish/screenshot.jpg</image>
![freegish-fs8](https://github.com/user-attachments/assets/cd3c34d0-b057-4118-8480-da0dcda9123f)
:)

2024-10-30 06:40 UTC, JanTrueno approved these changes

2024-10-30 11:24 UTC, JanTrueno approved these changes

2024-10-30 13:37 UTC, JanTrueno approved these changes

2024-10-30 13:41 UTC, merged