Updated Commander Genius to v3.5.1. Refactored to current PM standards.
PortsMaster/PortMaster-New pull request #879
Opened 2024-10-30 18:24 UTC by t0b10-r3tr0

Updated Commander Genius to v3.5.1. Refactored to current PM standards.

# New Port for Commander Genius (v3.5.1)

## Game Information
- **Title**: Commander Genius
- **URL**: https://gitlab.com/Dringgstein/Commander-Genius

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- The port contains the following structure:
  - cgenius/
      - conf/
      - gamedata/
      - libs/
      - license/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Commander Genius.sh
      

## Additional Resources
[**Community created content**](https://keenwiki.shikadi.net/wiki/Main_Page) can be downloaded and added either manually or automatically (with internet connection) through the provided launcher.

2024-10-30 20:03 UTC, cdeletre requested changes
Good job ! few thing to adjust and I think we're good to go :)

2024-10-30 20:03 UTC, cdeletre commented on ports/commander.genius/cgenius/CGeniusExe
Filesize has changed. Is it a new build ?

2024-10-30 20:03 UTC, cdeletre commented on ports/commander.genius/cgenius/libs/.gitkeep
`libs` folder must be renamed to `libs.aarch64` accroding to the new launch script

2024-10-30 23:11 UTC, t0b10-r3tr0 commented on ports/commander.genius/cgenius/CGeniusExe
Yes. New minor version bump. Binary changed from version 3.5.0 to [3.5.1](https://gitlab.com/Dringgstein/Commander-Genius/-/releases/v3.5.1).

2024-10-30 23:12 UTC, t0b10-r3tr0 commented on ports/commander.genius/cgenius/libs/.gitkeep
There are no libs included with this port. Should I just remove the directory?

2024-10-30 23:42 UTC, t0b10-r3tr0 commented on ports/commander.genius/screenshot.png
Great tool. Also ran it on the cover.png.

2024-10-30 23:43 UTC, t0b10-r3tr0 commented on ports/commander.genius/cgenius/libs/.gitkeep
Renamed as suggested.

2024-10-30 23:43 UTC, t0b10-r3tr0 commented
I have resolved the identified issues and this is, once again, ready for review.

2024-10-30 23:45 UTC, t0b10-r3tr0 commented on ports/commander.genius/cover.png
This has been done. Also ran pngquant against it.

2024-10-31 10:16 UTC, Cebion requested changes
- See Discord for comments, (porter, description and instruction length)

2024-10-31 16:05 UTC, t0b10-r3tr0 commented
Please see updated `ports.json`. I've incorporated the suggestions as provided in the PM Discord. Thanks folks.

2024-11-01 15:02 UTC, t0b10-r3tr0 commented
I've completed the final tweaks to the documentation and ports.json and am confident this can be reviewed.

2024-11-01 15:02 UTC, Cebion approved these changes

2024-11-01 18:27 UTC, cdeletre approved these changes

2024-11-02 08:30 UTC, merged