Added portfiles for Next Door
PortsMaster/PortMaster-New pull request #883
Opened 2024-10-30 21:49 UTC by slobters

# New Port for Next Door

## Game Information
- **Title**: Next Door
- **URL**: [Next Door](https://broelbrak.itch.io/nextdoor)

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [X] 640x480
- [ ] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-31 07:49 UTC, JanTrueno requested changes

2024-10-31 07:49 UTC, JanTrueno commented on ports/nextdoor/Next Door.sh
> +export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$GAMEDIR/libs.${DEVICE_ARCH}:$LD_LIBRARY_PATH"

Make sure to test again after this change.

2024-10-31 07:49 UTC, JanTrueno commented on ports/nextdoor/Next Door.sh
> +> "$GAMEDIR/log.txt" && exec > >(tee "$GAMEDIR/log.txt") 2>&1
Logging should be earlier in the script.

2024-10-31 19:20 UTC, JanTrueno approved these changes

2024-11-01 12:17 UTC, Cebion approved these changes

2024-11-01 12:17 UTC, merged