New Port: Doom II RPG
PortsMaster/PortMaster-New pull request #886
Opened 2024-11-01 14:59 UTC by Cebion

Game Information
Title: DOOM II RPG
URL:https://github.com/Cebion/DoomIIRPG-RE_pm

| Button | Action |
|--|--| 
|DPAD| Look Around|
|A| Interact/Shoot/Talk|
|B| Skip Turn|
|Y| Map|
|X| Inventory|
|L1/R1 | Strafe|
|L2/R2| Switch Weapons|
|Select| Menu|

CFW Tests:
[X] AmberELEC
[X] ArkOS
[X] MuOS
[X] ROCKNIX
-> [X] Panfrost
-> [X] Adreno
[X] Knulli (Optional)

Architectures: 
[X] Aarch64
[X] Panfrost (Mainline)

Resolutions: 
[] 480x320 (Optional)
[X] 640x480
[X] 720x720 (RGB30) (Optional)
[X] Higher resolutions (e.g., 1280x720)

2024-11-01 18:25 UTC, cdeletre requested changes

2024-11-01 18:25 UTC, cdeletre commented on ports/doom2rpg/gameinfo.xml
> +    <image>./doom2rpg/screenshot.jpg</image>
![doom2rpg-fs8](https://github.com/user-attachments/assets/adac1704-6d29-4baa-ae2e-79bebb506c42)

🥳

2024-11-01 18:25 UTC, cdeletre commented on ports/doom2rpg/Doom II RPG.sh
> +pm_platform_helper $GAMEDIR/$BINARY
For safety :)
```suggestion
pm_platform_helper "$GAMEDIR/$BINARY"
```

2024-11-02 01:56 UTC, tabreturn approved these changes

2024-11-02 08:00 UTC, kloptops approved these changes

2024-11-02 08:30 UTC, merged