Candy Bag
PortsMaster/PortMaster-New pull request #890
Opened 2024-11-02 06:35 UTC by tabreturn

# New Port for Candy Bag

## Game Information
- **Title**: Candy Bag
- **URL**: https://jontopielski.itch.io/candy-bag

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-11-02 08:10 UTC, kloptops requested changes

2024-11-02 08:10 UTC, kloptops commented on ports/candybag/port.json
> +            "aarch64"
```suggestion
```

Same with this one, uses love 11.5 runtime. Leave it blank. 😁

2024-11-03 03:08 UTC, kloptops approved these changes

2024-11-03 14:08 UTC, cdeletre approved these changes

2024-11-03 18:41 UTC, merged