Add Hallowe'en
PortsMaster/PortMaster-New pull request #907
Opened 2024-11-05 18:17 UTC by Slayer366

# New Port for Hallowe'en

## Game Information
- **Title**: Hallowe'en
- **URL**: [LinApple](https://github.com/Slayer366/linapple)

### CFW Tests
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
- [x] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

2024-11-05 19:36 UTC, Slayer366 commented
Whoops!  I wasn't paying attention when I dropped that marquee in the parent dir instead of the portdir where I should have had it.  Should be good now 👍

2024-11-06 08:51 UTC, Cebion requested changes

2024-11-06 08:51 UTC, Cebion commented on ports/hallowe_en/Hallowe'en (Apple II).sh
> +$ESUDO chmod 777 -R $GAMEDIR/*
Is this really needed? Upon installing the port via pm permissions are set for the whole folder.

2024-11-06 08:51 UTC, Cebion commented on ports/hallowe_en/README.md
> +git clone https://github.com/Slayer366/linapple
This should also be in the code block?

2024-11-06 08:51 UTC, Cebion commented on ports/hallowe_en/gameinfo.xml
> +		<marquee>./hallowe_en/marquee.png</marquee>
I'm not sure this is supported

2024-11-06 08:51 UTC, Cebion commented on ports/hallowe_en/hallowe_en/libs.aarch64/libSDL_image-1.2.so.0
Have you followed my suggestion in using my newly compiled sdl_image1.2? The list of libraries seems excessive to me.

2024-11-06 17:19 UTC, Slayer366 commented on ports/hallowe_en/hallowe_en/libs.aarch64/libSDL_image-1.2.so.0
I'll hit you up in Discord regarding this.  I'd love to reduce the number of libs used, but the few attempts I've made have resulted in a non-functioning app.  I am all for doing this if it's possible.

2024-11-06 18:13 UTC, Slayer366 commented on ports/hallowe_en/hallowe_en/libs.aarch64/libSDL_image-1.2.so.0
Incredible!  Thanks to you, I've significantly reduced the number of required libs across all 4 major CFWs.  I went from needing 18 to only needing 8.  Bloody amazing!

2024-11-07 19:39 UTC, Cebion approved these changes

2024-11-07 19:40 UTC, merged