New Port:  Roswyn & The Dragons
PortsMaster/PortMaster-New pull request #909
Opened 2024-11-06 09:14 UTC by Cebion

Game Information
Title: Roswyn & The Dragons
URL:https://github.com/Cebion/roswyn_pm

| Button | Action |
|--|--| 
|DPAD| Move|
|B | Select / Attack|
|Y| 1|
|X| 2|
|A| 3|
|Select| Exit|
|Start| Pause|

CFW Tests:
[X] AmberELEC
[x] ArkOS
[x] MuOS
[]x ROCKNIX
-> []x Panfrost
-> [x] Adreno (Optional)
[x] Knulli (Optional)

Resolutions: 
[X] 480x320 (Optional)
[X] 640x480
[x] 720x720 (RGB30) (Optional)
[x] Higher resolutions (e.g., 1280

2024-11-06 21:41 UTC, cdeletre requested changes

2024-11-06 21:41 UTC, cdeletre commented on ports/roswyn/Roswyn & The Dragons.sh
> +#bind_directories ~/.freegish $GAMEDIR/conf/.freegish
```suggestion
```

2024-11-09 12:12 UTC, kloptops approved these changes

2024-11-09 14:21 UTC, cdeletre approved these changes

2024-11-09 14:21 UTC, merged