New Port: Pingus
PortsMaster/PortMaster-New pull request #911
Opened 2024-11-06 15:00 UTC by Cebion

**Instructions to install the Testing Zip:**
Drop the .zip into your Portmaster autoinstall folder and run Portmaster.
or
run via ssh `harbourmaster install "zip url from discord" 

**Game Information**
Title: Pingus
URL:https://pingus.seul.org/download.html

| Button | Action |
|--|--| 
|DPAD| Move Screen|
|A/B | Mouse Left/Right Click|
|X| Slow Mouse (hold) |
|Y| Fast Forward|
|L1| Toggle Fullscreen|
|L2| Armageddon|
|Start| Pause|
**
CFW Tests:**
[x] AmberELEC
[x] ArkOS
[x] MuOS
[x]x ROCKNIX
-> []x Panfrost
-> [x] Adreno (Optional)
[x] Knulli (Optional)

Resolutions: 
[x] 480x320 (Optional)
[X] 640x480
[x] 720x720 (RGB30) (Optional)
[x] Higher resolutions (e.g., 1280

2024-11-06 20:49 UTC, cdeletre requested changes

2024-11-06 20:49 UTC, cdeletre commented on ports/pingus/Pingus.sh
> +# PORTMASTER: rrootage.zip, rRootage.sh
```suggestion
```

2024-11-08 17:06 UTC, Slayer366 approved these changes

2024-11-09 12:14 UTC, kloptops approved these changes

2024-11-09 14:14 UTC, cdeletre approved these changes

2024-11-09 14:14 UTC, merged