NEW: TS Underswap port
PortsMaster/PortMaster-New pull request #912
Opened 2024-11-06 22:51 UTC by Vector580

# New Port for TS!Underswap

## Game Information
- **Title**: TS!Underswap
- **URL**: https://github.com/Vector580/TSUnderswap-port.git

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ ] AmberELEC
- [x ] ArkOS
- [ x] ROCKNIX
- [x ] muOS

### Resolution Tests
Test all major resolutions:
- [x ] 480x320
- [x ] 640x480
- [ ] 720x720 (RGB30)
- [x ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-11-07 19:47 UTC, Cebion requested changes
Also gmloadernext license missing
https://github.com/JohnnyonFlame/gmloader-next/blob/master/LICENSE.md

2024-11-07 19:47 UTC, Cebion commented on ports/tsunderswap/TS Underswap.sh
> +# PORTMASTER: tsunderswap.zip, TS Underswap.sh
```suggestion
```
This is autogenerated by PortMaster

2024-11-07 19:47 UTC, Cebion commented on ports/tsunderswap/cover.png
Cover needs to either be a screenshot mix , or screenshot with logo but not only just the logo.

2024-11-09 12:20 UTC, kloptops approved these changes

2024-11-09 12:23 UTC, merged