Cally's Trials
PortsMaster/PortMaster-New pull request #966
Opened 2024-11-25 03:34 UTC by MadShmupper

# New Port for { Cally's Trials }

## Game Information
- **Title**: { Cally's Trials }
- **URL**: { https://store.steampowered.com/app/476510/Callys_Trials/ }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [ ] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-11-26 00:05 UTC, Slayer366 approved these changes

2024-11-27 01:57 UTC, cdeletre requested changes

2024-11-27 01:57 UTC, cdeletre commented on ports/callystrials/callystrials/libs/libcrypto.so.1.1
please add the [license](https://github.com/PortsMaster/PortMaster-New/blob/main/ports/minidoom2/minidoom2/licences/LICENSE.libcrypto.txt)

2024-11-27 01:57 UTC, cdeletre commented on ports/callystrials/callystrials/libs/libzip.so.5
Please add the [license](https://github.com/PortsMaster/PortMaster-New/blob/main/ports/minidoom2/minidoom2/licences/LICENSE.libzip.txt)

2024-11-27 01:57 UTC, cdeletre commented on ports/callystrials/callystrials/gamedata/splash.png
Is it the splash we want ? a white square ? :)

2024-11-27 03:16 UTC, MadShmupper commented on ports/callystrials/callystrials/libs/libcrypto.so.1.1
Added. Thank you🎩

2024-11-27 03:17 UTC, MadShmupper commented on ports/callystrials/callystrials/libs/libzip.so.5
Good to go. I also added them to my pr of Tamashii.🙂

2024-11-27 03:19 UTC, MadShmupper commented on ports/callystrials/callystrials/gamedata/splash.png
I took it out. It wasn't really needed. I had it in there as a gitkeeper type file and never took it out. Thank you🎩

2024-11-27 14:53 UTC, Cebion submitted a review, later dismissed

2024-11-28 03:55 UTC, cdeletre submitted a review, later dismissed

2024-11-28 07:50 UTC, merged