New Port: Super Amazing Wagon Adventure
PortsMaster/PortMaster-New pull request #968
Opened 2024-11-25 19:05 UTC by JanTrueno

## New Port: Super Amazing Wagon Adventure
**Description:** 
Super Amazing Wagon Adventure is a fast-paced 2d shooting game with a random story. You control a group of three migrants traveling west along a wagon trail. The game consists of short scenes that are sequenced together in a semi-random way to tell a crazy adventure story.

**Details:**
|Detail  | info |
|--|--|
| Engine | XNA|
| Architectures | 64bit|
| Aspect ratio | keeps 16:9  |
| Rumble support | Yes |
| Tested versions| [Steam](https://store.steampowered.com/app/250500/Super_Amazing_Wagon_Adventure/)| 
| Controls | native |

**Instructions:**
- Install portfiles with PM autoinstaller.
- Buy and install Super Amazing Wagon Adventure
- Copy all files to  the "wagonadvenure/gamedata" folder.

**Controls:**
|Controls|Action|
|--|--|
|A/B|Shoot|
|D-pad|Move|
|Start|Menu

## Requirements:
**Custom Firmwares:**
- [X] AmberELEC
- [X] ArkOS
- [x] ROCKNIX
- [x] MuOS
- [X] Knulli**
- [X] Crossmix **

**Drivers:** 
- [x] Mali
- [x] Panfrost
- [x] Adreno **

**Resolutions:** 
- [X] 480x320 **
- [x] 640x480
- [X] 720x720**
- [x] Higher resolutions 

## Notes:
- Thanks to [SparseVector](https://store.steampowered.com/search/?developer=sparsevector) for making this game.
- Make sure to have the mono runtime installed :slight_smile:
- Thanks to the FNA Framework devs.

-# ** = Optional requirement

2024-11-25 19:07 UTC, Cebion commented on ports/superamazingwagonadventure/Super Amazing Wagon Adventure.sh
> +source $controlfolder/tasksetter
Please add a little comment why you're using tasksetter

2024-11-25 19:09 UTC, Cebion requested changes

2024-11-25 19:09 UTC, Cebion commented on ports/superamazingwagonadventure/Super Amazing Wagon Adventure.sh
> +#export LD_LIBRARY_PATH="$GAMEDIR/libs:/usr/config/emuelec/lib32:/usr/lib32:$LD_LIBRARY_PATH"
Not needed? Remove

2024-11-25 19:09 UTC, Cebion commented on ports/superamazingwagonadventure/gameinfo.xml
> +    <image>./superamazingwagonadventure/cover.png</image>
What's with the long path. Should start with s sure but can be shortened no?
superwagon or whatever.

werenotdoingthesekindoflongnamesbecauseno

2024-12-01 10:29 UTC, kloptops approved these changes
Looks good, shortening the directory names wouldn't hurt.

2024-12-02 19:00 UTC, Cebion approved these changes

2024-12-03 03:31 UTC, cdeletre approved these changes

2024-12-03 08:24 UTC, merged