Clash Mastery
PortsMaster/PortMaster-New pull request #971
Opened 2024-11-27 09:50 UTC by tabreturn

# New Port for Clash Mastery

## Game Information
- **Title**: Clash Mastery
- **URL**: https://abhimonk.itch.io/clash-mastery

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-11-27 14:44 UTC, Cebion approved these changes

2024-11-27 15:13 UTC, cdeletre requested changes

2024-11-27 15:13 UTC, cdeletre commented on ports/clashmastery/port.json
> +        "runtime": "love2d",
love2d is included with PM-GUI [see here](https://github.com/PortsMaster/PortMaster-GUI/tree/main/PortMaster/runtimes/love_11.5)
```suggestion
        "runtime": null,
```

2024-11-28 03:54 UTC, cdeletre approved these changes

2024-11-28 07:56 UTC, Cebion approved these changes

2024-11-28 07:56 UTC, merged