make ready 2 run Demonstone64
PortsMaster/PortMaster-New pull request #973
Opened 2024-11-27 19:54 UTC by MadShmupper

# New Port for { Game Title }

## Game Information
- **Title**: { Demonstone64 }
- **URL**: { Link to project page or source control page }

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-11-27 21:25 UTC, Cebion requested changes

2024-11-27 21:25 UTC, Cebion commented on ports/demonstone64/port.json
> +    "Demonstone64.sh",
in gameainfo.xml you wrote ./Demonstone 64.sh
Here it is without space. make sure it is uniform

2024-11-27 21:25 UTC, Cebion commented on ports/demonstone64/port.json
> +      "MadShmupper"
You remofved jan from porters, this would wipe the portrers history of that port.

2024-11-27 21:25 UTC, Cebion commented on ports/demonstone64/port.json
> +    "desc": "With the "Magic Sword of Killing Anything in One Hit" in hand, you have returned to Castle Demonstone. But you can only take one hit as well! Dodge enemy attacks, vanquish the demon's mi
json error, use https://jsonlint.com/ for checking your json file

2024-11-28 08:00 UTC, Cebion approved these changes

2024-11-28 10:20 UTC, JanTrueno approved these changes

2024-11-28 10:21 UTC, merged