New Port: Sunset Shaped from matty
PortsMaster/PortMaster-New pull request #98
Opened 2024-02-15 11:10 UTC by Cebion

# New Port for Sunset Shaped

## Game Information
- **Title**: Sunset Shaped
- **URL**: https://bucketfish.itch.io/sunset-shaped

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

2024-02-15 11:17 UTC, kloptops requested changes
👎

2024-02-15 11:17 UTC, kloptops commented on ports/sunsetshaped/port.json
> +    "runtime": null,
No runtime specified in port.json.

2024-02-15 12:11 UTC, kloptops submitted a review, later dismissed
👍

2024-02-15 20:41 UTC, tabreturn commented on ports/sunsetshaped/port.json
Typo: missing space after stop at " atmosphere.Featuring "

2024-02-16 08:56 UTC, kloptops approved these changes
👍

2024-02-18 17:31 UTC, merged