Game got an update
PortsMaster/PortMaster-New pull request #983
Opened 2024-11-30 06:57 UTC by Fraxinus88

Updated to reflect new checksum and that game is not compatible with the expansion

2024-11-30 14:47 UTC, Cebion approved these changes

2024-12-01 01:28 UTC, tabreturn requested changes
There's a typo and a missing quote. Replace int_md with --

"inst_md": "Purchase the game from [**Steam**](https://store.steampowered.com/app/658150/Skeleton_Boomerang/)\n\n**Latest version(NOT compatible with expansion):**\nDownload the game and from your Steam library,  right click on Skeleton Boomerang >  Manage > Browse local files. Copy all the files from the folder to /ports/skeletonboomerang/gamedata\n\n**Prevamped version(better performance):**\nFrom your Steam Library, Right-Click Skeleton Boomerang and select Properties. Go to Betas and select \"prevamped- The pre-reVamped build of the game\" Download and install the prevamped version. Copy all the files from the folder to /ports/skeletonboomerang/gamedata\n\n**Note: This package is not compatible with the expansion :(**",

2024-12-01 10:33 UTC, kloptops approved these changes

2024-12-01 14:16 UTC, Cebion approved these changes

2024-12-01 14:17 UTC, merged