Hallowed Candy
PortsMaster/PortMaster-New pull request #985
Opened 2024-11-30 10:22 UTC by tabreturn

# New Port for Hallowed Candy

## Game Information
- **Title**: Hallowed Candy
- **URL**: https://projectlevel.itch.io/hallowed-candy

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] ROCKNIX
- [x] muOS

### Resolution Tests
Test all major resolutions:
- [ ] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-12-01 10:55 UTC, kloptops approved these changes

2024-12-01 14:16 UTC, Cebion requested changes
See comments

2024-12-01 14:16 UTC, Cebion commented on ports/hallowedcandy/gameinfo.xml
> +    <image>./hollowedcandy/screenshot.png</image>
hallowedcandy or hollowedcandy?

2024-12-02 18:53 UTC, Cebion approved these changes

2024-12-03 03:33 UTC, cdeletre approved these changes

2024-12-03 08:24 UTC, merged