New Port Mezzer
PortsMaster/PortMaster-New pull request #990
Opened 2024-12-01 14:16 UTC by Fraxinus88

# New Port for Mezzer

## Game Information
- **Title**: Mezzer
- **URL**: https://danieldavis.itch.io/mezzer

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-12-01 14:31 UTC, Cebion approved these changes

2024-12-02 18:52 UTC, Cebion requested changes

2024-12-02 18:52 UTC, Cebion commented on ports/mezzer/port.json
> +    "MEZZER",
```suggestion
    "MEZZER.sh",
```

2024-12-03 03:38 UTC, cdeletre submitted a review, later dismissed

2024-12-04 08:48 UTC, Cebion requested changes

2024-12-04 08:48 UTC, Cebion commented on ports/mezzer/MEZZER.sh
> +printf "\033c" > /dev/tty0
no longer used
```suggestion
printf "\033c" > /dev/tty0
```

2024-12-04 18:31 UTC, Cebion requested changes

2024-12-04 18:31 UTC, Cebion commented on ports/mezzer/MEZZER.sh
> +    echo "data.win not in gamedata folder or game has been patched."
```suggestion
    pm_message "data.win not in gamedata folder or game has been patched."
```

2024-12-04 18:31 UTC, Cebion commented on ports/mezzer/MEZZER.sh
> +    echo "Mezzer.exe not detected in /mezzer"
```suggestion
    pm_message "Mezzer.exe not detected in /mezzer"
```

2024-12-06 23:43 UTC, Cebion approved these changes

2024-12-06 23:43 UTC, merged