New Port: Titanion
PortsMaster/PortMaster-New pull request #997
Opened 2024-12-02 18:42 UTC by Cebion

Game Information
Title: Titanion (Shump)
URL: https://www.asahi-net.or.jp/~cs8k-cyu/windows/ttn_e.html

| Button | Action |
|--|--| 
|DPAD| Move | 
|A| Shoot |Hold down a button to fire automatically. |
|B| Capture beam / Provocation beam| 

CFW Tests:
[x] AmberELEC
[x] ArkOS
[x] MuOS
[x ROCKNIX
-> [x] Panfrost
-> [x] Adreno (Optional)
[x] Knulli (Optional)

Resolutions: 
[] 480x320 (Optional)
[x] 640x480
[x] 720x720 (RGB30) (Optional)
[x] Higher resolutions (e.g., 1280)

2024-12-02 19:01 UTC, Slayer366 requested changes

2024-12-02 19:01 UTC, Slayer366 commented on ports/titanion/titanion/titanion.gptk
Is this lowercase filename going to cause an issue since you have $BINARY in the shell script set for the executable having a capital 'T'?

2024-12-02 19:04 UTC, Cebion commented on ports/titanion/titanion/titanion.gptk
I don't see it :D
The binary is called Titanion as is the binary=

2024-12-02 19:17 UTC, Slayer366 commented on ports/titanion/titanion/titanion.gptk
Erm, I mean shouldn't this be Titanion.gptk instead of titanion.gptk?

2024-12-02 19:49 UTC, Cebion commented on ports/titanion/titanion/titanion.gptk
> Erm, I mean shouldn't this be Titanion.gptk instead of titanion.gptk?

good catch

2024-12-02 20:11 UTC, Slayer366 approved these changes

2024-12-03 03:43 UTC, cdeletre approved these changes

2024-12-03 08:23 UTC, merged